### ISSUE TITLE
`flyctl secrets import -a` with alternate app name fails

### ISSUE THREAD

**Issue by a-type** [superfly/flyctl#1016]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

* Operating system: `ubuntu-latest` (Github Actions), Windows 11
* `fly version`: `v0.0.334`

** Paste your `fly.toml`

```toml
# fly.toml file generated for my-app on 2022-06-17T14:00:16-04:00

app = "my-app"

[build]
dockerfile = "Dockerfile.api"

[[services]]
internal_port = 4080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true
[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
restart_limit = 0
timeout = "2s"

```

** Command output: **

(in Github Actions)

```text
WARN app flag '***-pr-478' does not match app name in config file '***'
? Continue using '***-pr-478' (y/N) 25lOops, something went wrong! Could you try that again?
Error: Process completed with exit code 3.
```

(from Windows local CLI usage)

```text
PS D:\work\app> Get-Content .env.staging.fly | flyctl secrets import -a my-app-staging
WARN app flag 'my-app-staging' does not match app name in config file 'my-app'
? Continue using 'my-app-staging' (y/N) Error Incorrect function.
```

The command immediately terminates with the error, no input is gathered.

Additionally, this command should take a `-y` flag for CLI environments, so that we can bulk add secrets to new app deploys (like PR preview apps) with a different name from the base config.

## Current workaround

Rename the app in `fly.toml` before running the command.
