### ISSUE TITLE
DOCKER_HOST ignored in later steps in `fly deploy`

### ISSUE THREAD

**Issue by acuteaura** [superfly/flyctl#1041]
**Describe the bug**
`flyctl deploy` will correctly detect `DOCKER_HOST` during initial container pulls, but then fail in a later step with

```
Error failed to fetch an image or build from source: executing lifecycle: failed to create 'creator' container: Error response from daemon: container create: statfs /var/run/docker.sock: permission denied
```

where

```
$ env | grep DOCKER_HOST
DOCKER_HOST=unix:///var/run/user/1000/podman/podman.sock
```

initial correct detection

```
==> Verifying app config
--> Verified app config
==> Building image
==> Building image with Buildpacks
--> docker host: 4.1.1 linux amd64
```

* Operating system
Fedora 36

* `fly version`

```
$ fly version
flyctl v0.0.341 linux/amd64 Commit: 44ea488 BuildDate: 2022-06-27T23:37:56Z
```

** Paste your `fly.toml`

```toml
# fly.toml file generated for github-authn-checker on 2022-06-28T15:14:01+02:00

app = "[snip]"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

** Command output: **

```text
$ fly deploy --verbose
==> Verifying app config
--> Verified app config
==> Building image
==> Building image with Buildpacks
--> docker host: 4.1.1 linux amd64
244522c16fd3: Already exists
d74fb5e7507d: Already exists
82f200a97af7: Already exists
357fefdf9bc9: Already exists
452273c8f8b2: Already exists
98438d9c08b1: Already exists
bac15eba08bc: Already exists
5f78ad9fb23b: Already exists
09bcc3a11e53: Already exists
ab5047eccf2c: Already exists
72b248d8840f: Already exists
3cb5b33fc004: Already exists
8a9f04d5a383: Already exists
a187311c669e: Already exists
94ad14ff029b: Already exists
3e3de149b610: Already exists
e02a34461639: Already exists
1e1d033f358e: Already exists
6585c7ca3dd5: Already exists
823dab4e6f71: Already exists
0530e5c87aae: Already exists
c1b47f3be08a: Already exists
7cea3fe76fa6: Already exists
1060137bb4a4: Already exists
8dbf895d9b88: Already exists
4b7a3a956607: Already exists
dbe6aa5f1d01: Already exists
806680c5da03: Already exists
607425cbcd39: Already exists
baf91402f1dd: Already exists
288c3fa81b55: Already exists
d83410d57df6: Already exists
81998f97d290: Already exists
af297f843218: Already exists
8a5443d3bfb5: Already exists
c590da580225: Already exists
73eb891ed9ce: Already exists
f28da8fc2058: Already exists
fed13f37137e: Already exists
93db30b468f4: Already exists
78ba6e63e316: Already exists
05d441f4b12d: Already exists
aca854443073: Already exists
202d31b60d84: Already exists
6ba5f9041ac0: Already exists
bb5184e15d43: Already exists
ba4194ba0a69: Already exists
8e82b375e212: Already exists
3363e5573282: Already exists
f4fdc6d76f4a: Already exists
24aa8aedaa57: Already exists
a29c21aea15d: Already exists
60d93c1547f6: Already exists
88b7955b77ba: Already exists
7599299b58d6: Already exists
0410ebbcaa29: Already exists
7dbe82201763: Already exists
921a23bb2159: Already exists
3e01ae414a68: Already exists
cdcec7a546b2: Already exists
566c5c33abc7: Already exists
ab7be784ea3f: Already exists
b68855d7cd2f: Already exists
57d7c3c85858: Already exists
b17d081eb590: Already exists
872d4e9ad910: Already exists
e4137f835a94: Already exists
4b63415a5236: Already exists
93d8352efdc1: Already exists
f83c193cd763: Already exists
15e7ad901226: Already exists
3e99a981936e: Already exists
c0c1d5d746a6: Already exists
a773410757b5: Already exists
b2c4726ad244: Already exists
5e140aefe5bd: Already exists
3c71e15aea89: Already exists
457f86152e96: Already exists
f98d1bba23c9: Already exists
7a7c37393e38: Already exists
046e21d676ba: Already exists
15964dff2ce4: Already exists
7d84d1aae436: Already exists
4bbc170ef914: Already exists
76982998da52: Already exists
f8982a097916: Already exists
6b4b6cb382e8: Already exists
e8b147f2ad55: Already exists
fb579664cd9d: Already exists
9b5666b6173a: Already exists
dc8ff4e230ef: Already exists
b6e8164c9b8b: Already exists
fa244c949396: Already exists
1fe2e724d812: Already exists
72ad9888618d: Already exists
4f4fb700ef54: Already exists
2cd0db58887b: Download complete
2f6c8e9e25f9: Already exists
a3347941d813: Already exists
d72d35cb3cb4: Already exists
8a9f04d5a383: Already exists
dc2098d20958: Download complete
4b7a3a956607: Already exists
ab7be784ea3f: Already exists
dc8ff4e230ef: Already exists
8dbf895d9b88: Already exists
c1b47f3be08a: Already exists
7dbe82201763: Already exists
a29c21aea15d: Already exists
3c71e15aea89: Already exists
6ba5f9041ac0: Already exists
7d84d1aae436: Already exists
05d441f4b12d: Already exists
607425cbcd39: Already exists
88b7955b77ba: Already exists
3e01ae414a68: Already exists
566c5c33abc7: Already exists
ba4194ba0a69: Already exists
72b248d8840f: Already exists
a9ffc1763af7: Download complete
Error failed to fetch an image or build from source: executing lifecycle: failed to create 'creator' container: Error response from daemon: container create: statfs /var/run/docker.sock: permission denied
```
