### ISSUE TITLE
`flyctl deploy` certificate signed by unknown authority with paketo go buildpack

### ISSUE THREAD

**Issue by hherman1** [superfly/flyctl#1079]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
I can no longer deploy my repo. I haven't changed anything about my fly.toml, and this has worked in the past, but recently stopped working.

* Operating system
MacOS
* `fly version`
`fly v0.0.323 darwin/amd64 Commit: c4d6328 BuildDate: 2022-04-24T11:33:12Z`

** Paste your `fly.toml`

```toml
# fly.toml file generated for gorgina on 2022-04-24T22:50:55-07:00

app = "gorgina"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

** Command output: **

```text
base: Pulling from paketobuildpacks/builder
Digest: sha256:6097f96585bd7a308495b26f313c91fa68d88027a30580ab8eda244217d232a3
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:1e2a282085f1b7a0fa1d96bd8509378270ab752c6d8042472a95df2bf5e1d6ea
Status: Image is up to date for paketobuildpacks/run:base-cnb
latest: Pulling from paketo-buildpacks/go
Digest: sha256:7b70b114ac4fe8d8c201965a99ac204de6a4e848c894eae58abe7b11eb4a0081
Status: Image is up to date for gcr.io/paketo-buildpacks/go:latest
[36m===> DETECTING[0m
5 of 9 buildpacks participating
paketo-buildpacks/ca-certificates 3.2.4
paketo-buildpacks/go-dist         1.2.2
paketo-buildpacks/git             0.4.2
paketo-buildpacks/go-mod-vendor   0.6.2
paketo-buildpacks/go-build        1.1.4
[36m===> ANALYZING[0m
Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
Restoring metadata for "paketo-buildpacks/go-dist:go" from cache
Restoring metadata for "paketo-buildpacks/go-mod-vendor:mod-cache" from cache
Restoring metadata for "paketo-buildpacks/go-build:targets" from app image
Restoring metadata for "paketo-buildpacks/go-build:gocache" from cache
[36m===> RESTORING[0m
Restoring data for "paketo-buildpacks/go-dist:go" from cache
Restoring data for "paketo-buildpacks/go-mod-vendor:mod-cache" from cache
Restoring data for "paketo-buildpacks/go-build:gocache" from cache
[36m===> BUILDING[0m
[34m[0m
[34m[1mPaketo CA Certificates Buildpack[0m[34m 3.2.4[0m
  [34;2;3mhttps://github.com/paketo-buildpacks/ca-certificates[0m
  [34mLaunch Helper[0m: [33mContributing[0m to layer
[2m    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper[0m
Paketo Go Distribution Buildpack 1.2.2
  Resolving Go version
    Candidate version sources (in priority order):
      go.mod    -> ">= 1.18"
      <unknown> -> ""

    Selected Go version (using go.mod): 1.18.3

  Reusing cached layer /layers/paketo-buildpacks_go-dist/go

[33;1mWarning: [0mBOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
[33;1mWarning: [0mBOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Paketo Git Buildpack 0.4.2
  Configuring build environment
    REVISION -> "85dc5f4982b941d254137d84777f561305e098ed"

  Configuring launch environment
    REVISION -> "85dc5f4982b941d254137d84777f561305e098ed"

Paketo Go Mod Vendor Buildpack 0.6.2
  Checking module graph
    Running 'go mod graph'
      Failed after 1.17s
        go: github.com/google/uuid@v1.3.0: Get "https://proxy.golang.org/github.com/google/uuid/@v/v1.3.0.mod": x509: certificate signed by unknown authority
exit status 1
[31;1mERROR: [0mfailed to build: exit status 1
```
