### ISSUE TITLE
Build Args with comma in value throws "invalid build args" error

### ISSUE THREAD

**Issue by samharnack** [superfly/flyctl#1082]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

Same issue a #520

Running `fly deploy --build-arg SOME_BUILD_ARG="a,b"` throws the following:

```
==> Verifying app config
--> Verified app config
==> Building image
Error failed to fetch an image or build from source: invalid build args: 'b': must be in the format NAME=VALUE
```

I've also tried:

```
fly deploy --build-arg SOME_BUILD_ARG=a,b  
fly deploy --build-arg SOME_BUILD_ARG="a\,b"
fly deploy --build-arg SOME_BUILD_ARG=a\,b

export SOME_BUILD_ARG_VALUE="a,b"
fly deploy --build-arg SOME_BUILD_ARG=$SOME_BUILD_ARG_VALUE
```

* Operating system
* `fly version`

fly v0.0.353 darwin/arm64 Commit: a6e61fa6 BuildDate: 2022-07-12T11:36:55Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for APPNAME on 2022-07-17T08:16:59-07:00

app = "APPNAME"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
$ fly deploy --build-arg SOME_BUILD_ARG="a,b"              
                
==> Verifying app config
--> Verified app config
==> Building image
Error failed to fetch an image or build from source: invalid build args: 'b': must be in the format NAME=VALUE
```
