### ISSUE TITLE
flyctl launch doesn't detect relative docker file correctly

### ISSUE THREAD

**Issue by CoenraadS** [superfly/flyctl#1101]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

I have a dockerfile in the folder:
`"C:\Users\Coenraad\Documents\Projects\Easy-Cover\EasyCover\EasyCover\Dockerfile"`

I ran flyctl from one directory above

`C:\Users\Coenraad\Documents\Projects\Easy-Cover\EasyCover>flyctl launch --dockerfile "./EasyCover/Dockerfile"`

This created the .toml file I put below

However the next time I run `flyctl launch` (without dockerfile args, using toml file)
`C:\Users\Coenraad\Documents\Projects\Easy-Cover\EasyCover>flyctl launch`

`Error Rel: can't make EasyCover\Dockerfile relative to C:\Users\Coenraad\Documents\Projects\Easy-Cover\EasyCover`

* Operating system Windows 10
* `fly version` flyctl.exe v0.0.359 windows/amd64 Commit: 15b0f802 BuildDate: 2022-07-23T12:26:56Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for snowy-sky-5864 on 2022-07-24T11:49:59+02:00

app = "snowy-sky-5864"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "/EasyCover/Dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
flyctl launch --verbose
An existing fly.toml file was found for app snowy-sky-5864
App is not running, deploy...
Deploying snowy-sky-5864
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8080
Remote builder fly-builder-old-shadow-2226 ready
==> Creating build context
Error Rel: can't make EasyCover\Dockerfile relative to C:\Users\Coenraad\Documents\Projects\Easy-Cover\EasyCover
```
