### ISSUE TITLE
"remote builder app unavailable" deploying via nixpacks

### ISSUE THREAD

**Issue by justinmoon** [superfly/flyctl#1131]
**Describe the bug**

"remote builder app unavailable" error when attempting to deploy with nixpacks

* Operating system
MacOS 12.3.1 (M1 processor)
* `fly version`
fly v0.0.364 darwin/arm64 Commit: 105ccd25 BuildDate: 2022-08-03T02:58:44Z

** Paste your `fly.toml`

```toml
# paste your config file here
# fly.toml file generated for slipbox on 2022-06-12T20:59:12-05:00

app = "dark-leaf-1572"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[mounts]
  source="dark_leaf_data"
  destination="/data"

[env]
  DB = "/data/slipbox.db"
  # STORAGE = "/data/storage"
  STORAGE = "/workspace/public/storage"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
$ fly deploy --nixpacks
==> Verifying app config
--> Verified app config
==> Building image
WARN Remote builder did not start in time. Check remote builder logs with `flyctl logs -a fly-builder-red-wood-7347`
Error failed to fetch an image or build from source: remote builder app unavailable
``````
