### ISSUE TITLE
Ruby version is incorrectly inferred from Gemfile when not exact

### ISSUE THREAD

**Issue by palkan** [superfly/flyctl#1242]
**Describe the bug**

When Ruby version is specified using constraints (`>`, `~>`), the RUBY_VERSION build arg in incorrectly inferred.

* `fly version`: fly v0.0.383 darwin/arm64 Commit: 16a17b20 BuildDate: 2022-08-25T21:59:49Z

* `Gemfile`

```ruby
ruby "~> 3.1.0"
```

**Expected build args**

```toml
[build]
  [build.args]
    RUBY_VERSION = "3.1.0" # ideally, there should be 3.1
```

**Actual build args**

```toml
[build]
  [build.args]
    RUBY_VERSION = "~> 3.1.0"
```
