### ISSUE TITLE
Turboku: converts incorrectly Procfile commands with double parentheses

### ISSUE THREAD

**Issue by skatkov** [superfly/flyctl#1265]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
I've migrated a heroku app with turboku. It had a following Procfile:

```Procfile
web: bundle exec puma -C config/puma.rb
worker: bundle exec good_job start --max-threads=1 & bundle exec good_job --queues="default, mailer" --max-threads=1 & wait -n
```

* Operating system
Update available 0.0.387 -> v0.0.388.
Run "flyctl version update" to upgrade.
flyctl v0.0.387 linux/amd64 Commit: d46c14f3 BuildDate: 2022-09-01T21:55:51Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for briefcake on 2022-09-11T00:56:37+07:00

app = "briefcake"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "bundle exec rake db:migrate"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bin/rails fly:server"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[processes]
  app = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec good_job start --max-threads=1 & bundle exec good_job --queues=\"default, mailer\" --max-threads=1 & wait -n"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  cache_key = "___app_public"
  guest_path = "/app/public"
  processes = []
  url_prefix = "/"

```

** Command output: **

```text
2022-09-10T18:00:48.000 [info] Preparing to run: `/bin/bash /app/entrypoint.sh bundle exec good_job start --max-threads=1 & bundle exec good_job --queues=default, mailer --max-threads=1 & wait -n` as heroku
2022-09-10T18:00:48.000 [info] 2022/09/10 18:00:48 listening on [fdaa:0:4c48:a7b:c207:84f2:dde0:2]:22 (DNS: [fdaa::3]:53)
2022-09-10T18:00:49.000 [info] ERROR: "good_job start" was called with arguments ["mailer"]
2022-09-10T18:00:49.000 [info] Usage: "good_job start"

```

In this case double parentheses could not be found in that command. But we can make it work, by tweaking fly.toml and changing to single parentheses

`bundle exec good_job --queues='default, mailer' --max-threads=1`
