### ISSUE TITLE
Stuck When Scale

### ISSUE THREAD

**Issue by bogordesaincom** [superfly/flyctl#1270]
VM stuck when scale to 1024 

<img width="1307" alt="Jepretan Layar 2022-09-13 pukul 12 28 33" src="https://user-images.githubusercontent.com/51335197/189817861-581a0a2d-cbe9-4672-a99c-7ca689413cc7.png">

**Describe the bug**
VM stuck when scale to 1024, i was try restart but not response

* Operating system
* `fly version` 0.0.389

** Paste your `fly.toml`

```toml
app = "mariabigwp"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
    destination = "/var/lib/mysql"
    source = "bigwp_storage"
[env]
    MARIADB_DATABASE = "****"
    MARIADB_USER = "****"

[build]
    image = "mariadb:latest"

```

** Command output: **

```text
when i relaunch my app mariadb 
Error App is unchanged, skipping release
```
