### ISSUE TITLE
fly deploy with Buildpacks failed due to dead docker hub link

### ISSUE THREAD

**Issue by mirshko** [superfly/flyctl#1288]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

Using a node fastify server setup attempting to deploy to Fly using the following `[build]` setting in the `fly.toml` file

```toml
[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]
```
the following error occurs: 

```text 
Error failed to fetch an image or build from source: failed to fetch builder image 'index.docker.io/paketobuildpacks/builder:base': resolve auth for ref index.docker.io/paketobuildpacks/builder:base: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

* Operating system
* `fly version`

fly v0.0.393 darwin/arm64 Commit: b792bf9c BuildDate: 2022-09-16T18:36:20Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for twilight-paper-3305 on 2022-09-20T19:24:54+02:00

app = "twilight-paper-3305"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
fly deploy
==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-rough-dust-3816 ready
==> Building image with Buildpacks
--> docker host: 20.10.12 linux x86_64
Error failed to fetch an image or build from source: failed to fetch builder image 'index.docker.io/paketobuildpacks/builder:base': resolve auth for ref index.docker.io/paketobuildpacks/builder:base: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

It seems that the `index.docker.com` domain has been changed to `hub.docker.com` and there is not a proper redirect setup on their end.
