### ISSUE TITLE
Can't launch a machine with a custom name

### ISSUE THREAD

**Issue by StarpTech** [superfly/flyctl#1292]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

First, `flyctl machine launch` does not take `app` from the config into account. Second, I can't configure a custom name.

* Ubuntu
* `flyctl v0.0.395 linux/amd64 Commit: 01205c00 BuildDate: 2022-09-21T21:29:50Z`

** Paste your `fly.toml`

```toml
app = "test"

[env]
RELEASE = "1"
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false
```

**Command output:**

```text
Choose an app name (leave blank to generate one): 
```
