### ISSUE TITLE
`fly deploy` resets vm size to shared-cpu-1x 256MB on machine-based apps

### ISSUE THREAD

**Issue by lewisl9029** [superfly/flyctl#1310]
**Describe the bug**

Was asked to report here from the forum thread: https://community.fly.io/t/preview-deploying-applications-on-machines-with-flyctl/6171/8?u=lewis

> I had my app set to use 2048MB memory and 2 shared cpus through fly machine update. But running fly deploy seems to have reset it to 1 shared cpu and 256MB memory.

This is reproducible every time I deploy. For now I've been working around it by updating my CI script to set the size immediately after each deploy. Works for now since there's barely any traffic, but obviously not sustainable.

Doesn't seem to be OS specific since it happens when I do `fly deploy` in CI (linux) as well as locally (macOS).

* Operating system: macOS Monterey 12.6
* `fly version`: fly v0.0.396 darwin/arm64 Commit: edf8f512 BuildDate: 2022-09-23T19:34:38Z

** Paste your `fly.toml`

```toml
app = "reflame-deployer"

[build]

[http_service]
  internal_port = 58001
  force_https = true

  [http_service.concurrency]
    hard_limit = 10
    soft_limit = 2
    type = "requests"

[deploy]
```
