### ISSUE TITLE
fly.toml files which only specify a build target do not deploy the correct target

### ISSUE THREAD

**Issue by mglazer** [superfly/flyctl#1319]
**Describe the bug**

I have a `fly.toml` with this content:

```toml
app = "api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  # https://github.com/superfly/flyctl/pull/1291
  build-target = "api-web"
```

My `Dockerfile` has multiple targets in it.

* OSX
* `0.0.398`

** Command output: **

I'd expect this to deploy the target with `api-web`, instead it deploys some other target in my `Dockerfile`

I have addressed this with: https://github.com/superfly/flyctl/pull/1291, the obvious workaround is:

```toml
app = "api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  # https://github.com/superfly/flyctl/pull/1291
  dockerfile = "Dockerfile"
  build-target = "api-web"
```

But that should be unnecessary.

Just filing this issue to hopefully get the bug fix merged.
