### ISSUE TITLE
`fly.toml` is not present in image produced by `flyctl.deploy

### ISSUE THREAD

**Issue by vbrandl** [superfly/flyctl#1330]
I have an app that relies on the state of the git repository at build time to generate version information in the footer. If there are any uncommitted changes in the repository at build time, a `-dirty` flag is appended to the git tag or commit ref.

When building the docker image directly using `docker build`, everything works as expected, the repository is clean and the proper version info is generated. But when building the image using `flyctl deploy --build-only --local-only`, the `fly.toml` is not present, which causes all deployments to include the `-dirty` flag. I'm not sure if `fly.toml` is actively deleted or if it is ignored because flyctl extends `.dockerignore` or something like that.

Is there a way to include and not delete `fly.toml` when building and deploying an image?

* NixOS 22.05
* `flyctl v0.0.328 linux/amd64 Commit: v0.0.328 BuildDate: 1970-01-01T00:00:00Z`
* The repoistory in question is https://github.com/vbrandl/petnames-generator but I can create a minimal testcase if that helps.

```toml
app = "petnames"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
cmd = "./petnames-generator"

[env]
PORT = "8080"

[metrics]
port = 3000
path = "/metrics"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
port = "8080"
restart_limit = 6
timeout = "2s"
```
