### ISSUE TITLE
build.image removed from template fly.toml

### ISSUE THREAD

**Issue by carlsverre** [superfly/flyctl#1340]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
If you run `fly launch --copy-config` with an existing fly.toml which includes `build.image`, the resulting copied config file will not have `build.image` defined.

Initial `fly.toml`:
```toml
[build]
  image = "ghcr.io/singlestore-labs/singlestoredb-dev"

[[services]]
  internal_port = 3306
  protocol = "tcp"

  [[services.ports]]
    port = 3306
```

`fly.toml` after running `fly launch --copy-config`:
```toml
# fly.toml file generated for weathered-bush-6984 on 2022-10-06T15:45:39-07:00

app = "weathered-bush-6984"

[[services]]
  internal_port = 3306
  protocol = "tcp"

  [[services.ports]]
    port = 3306
```

* Operating system
* `fly version` = v0.0.404
