### ISSUE TITLE
Exit code 1 after `deployed successfully`

### ISSUE THREAD

**Issue by alexander-applyinnovations** [superfly/flyctl#1392]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
When deploying with flyctl deploy, the deployment succeeds but the command returns an exit code 1 and fails the github action.

* Operating system
Ubuntu 20.04.5 LTS
* `fly version`
flyctl 0.0.414

**Paste your `fly.toml`**

```toml
app = "project-name-cms"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "yarn deploy"
  strategy = "bluegreen"

[env]
  PORT = "8080"
  PRIMARY_REGION = "syd"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

**Command output:**
```text
flyctl deploy --remote-only --auto-confirm --now --verbose --app project-name-cms --region syd --env ENV_NAME=${{ env.ENV_NAME }} --env S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} --env S3_REGION=${{ secrets.S3_REGION }} --env S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} --env S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}

==> Verifying app config
--> Verified app config
==> Building image
Waiting for remote builder fly-builder-little-night-4837...
Remote builder fly-builder-little-night-4837 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
Sending build context to Docker daemon  316.3kB

#1 [internal] load remote build context
#1 DONE 0.0s

#2 copy /context /
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/node:16-alpine
#3 DONE 0.5s

#4 [builder 1/6] FROM docker.io/library/node:16-alpine@sha256:2175727cef5cad4020cb77c8c101d56ed41d44fbe9b1157c54f820e3d345eab1
#4 resolve docker.io/library/node:16-alpine@sha256:2175727cef5cad4020cb77c8c101d56ed41d44fbe9b1157c54f820e3d345eab1 done
#4 DONE 0.0s

#5 [runner 2/6] WORKDIR /app
#5 CACHED

#6 [runner 3/6] RUN addgroup --system --gid 1001 nodejs
#6 CACHED

#7 [runner 4/6] RUN adduser --system --uid 1001 nextjs
#7 CACHED

	 Preparing to run: `docker-entrypoint.sh yarn deploy` as nextjs
	 2022/10/18 01:40:45 listening on [fdaa:0:bacf:a7b:9e6a:c7ca:bbfa:2]:22 (DNS: [fdaa::3]:53)
	 yarn run v1.22.19
	 $ keystone prisma migrate deploy
	 Prisma schema loaded from schema.prisma
	 Datasource "postgresql": PostgreSQL database "focapp_github_action_build_image_cms", schema "public" at "top2.nearest.of.focapp-github-action-build-image-db.internal:5432"
	 Prisma schema loaded from schema.prisma
	 Datasource "postgresql": PostgreSQL database "focapp_github_action_build_image_cms", schema "public" at "top2.nearest.of.focapp-github-action-build-image-db.internal:5432"
	 4 migrations found in prisma/migrations
	 4 migrations found in prisma/migrations
	 Prisma schema loaded from schema.prisma
	 Datasource "postgresql": PostgreSQL database "focapp_github_action_build_image_cms", schema "public" at "top2.nearest.of.focapp-github-action-build-image-db.internal:5432"
	 4 migrations found in prisma/migrations
	 Prisma schema loaded from schema.prisma
	 Datasource "postgresql": PostgreSQL database "focapp_github_action_build_image_cms", schema "public" at "top2.nearest.of.focapp-github-action-build-image-db.internal:5432"
	 4 migrations found in prisma/migrations
	 No pending migrations to apply.
	 Done in 8.84s.
	 No pending migrations to apply.
	 Done in 8.84s.
	 No pending migrations to apply.
	 Done in 8.84s.
	 No pending migrations to apply.
	 Done in 8.84s.
	 Starting clean up.
	 Starting clean up.
	 Starting clean up.
	 Starting clean up.
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: 249766e)...
	 Setting up swapspace version 1, size = 536866816 bytes
	 UUID=962b6500-b059-4608-95e1-ded82498a548
	 Preparing to run: `docker-entrypoint.sh yarn deploy` as nextjs
	 2022/10/18 01:40:45 listening on [fdaa:0:bacf:a7b:9e6a:c7ca:bbfa:2]:22 (DNS: [fdaa::3]:53)
	 yarn run v1.22.19
	 $ keystone prisma migrate deploy
	 Prisma schema loaded from schema.prisma
	 Datasource "postgresql": PostgreSQL database "focapp_github_action_build_image_cms", schema "public" at "top2.nearest.of.focapp-github-action-build-image-db.internal:5432"
	 4 migrations found in prisma/migrations
	 No pending migrations to apply.
	 Done in 8.84s.
	 Starting clean up.
==> Monitoring deployment

v4 is being deployed
753b2eef: syd running healthy
753b2eef: syd running healthy [health checks: 1 total, 1 passing]
--> v4 deployed successfully
Error: Process completed with exit code 1.
```
