### ISSUE TITLE
Next.js Dockerfile template causes volume permissions problems

### ISSUE THREAD

**Issue by oliverjam** [superfly/flyctl#1400]
`fly launch` generates a `Dockerfile` that causes volume permissions problems (e.g. with SQLite).

I'm not really a Docker person so I don't know exactly why the Next.js Dockerfile switches to a new user:

https://github.com/superfly/flyctl/blob/a5afeb1dabe72ada9d3bb5b39eb629f2b3ca0b25/scanner/templates/nextjs/Dockerfile#L31-L32

but this seems to cause permissions problems in an added volume. When I added a volume and pointed SQLite at it I got runtime errors as soon as my app tried to write:

```
SqliteError: attempt to write a readonly database
```

I figured this was because the `next` user created in the Dockerfile doesn't have permissions to the volume, so I deleted those lines from the Dockerfile and it worked fine.

Is there a reason that stuff is there? The Remix Dockerfile template doesn't have anything similar.

* `macOS Monterey 12.6`
* `fly v0.0.414 darwin/arm64`

```toml
app = "next-thing"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source="data"
  destination="/data"
```
