### ISSUE TITLE
flyctl ssh console -C "..." doesn't handle environment variable

### ISSUE THREAD

**Issue by frozar** [superfly/flyctl#1442]
# Bug description

I want to use the `fly ssh console` with the `-C` argument to launch a command on the machine which hosts my database. But when I try the following command, I get an error:

```sh
$ fly ssh console -a flaxidb -C "PGPASSWORD=gArBageGarBage psql -h 127.0.0.1 -U postgres -c \"SELECT version()\""
Connecting to fdaa:0:cbd7:a7b:5adc:2:c023:2... complete
exec: "PGPASSWORD=gArBageGarBage": executable file not found in $PATH
```

It seems that my environment variable is understood as a program name whereas it not the case, and this variable is necessary to execute `psql` in this way (with the correct token in the `PGPASSWORD` environment variable).

Is it a bug?

Do you have a workaround for me?

# Details

## `fly version`

```sh
$ fly version
flyctl v0.0.429 linux/amd64 Commit: 6db701e0 BuildDate: 2022-11-04T13:51:06Z
```

## TOML configuration

My application is just the database server. I rely on the official repository of `postgres-ha`:  
https://github.com/fly-apps/postgres-ha

But as I needed to custom the Dockerfile, I fork it here:
https://github.com/frozar/postgres-ha

My `fly.toml` file:

```toml
app = "flaxidb"
kill_signal = "SIGTERM"
kill_timeout = 300

[checks]
  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"
  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"
  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

[env]
  BACKEND_STORE = "consul"
  PRIMARY_REGION = "ord"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_consul = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  source = "pg_data"
```
