### ISSUE TITLE
fly launch doesn't provide a helpful error message when rerunning after an error

### ISSUE THREAD

**Issue by mhlakhani** [superfly/flyctl#1447]
**Describe the bug**
I tried running `flyctl launch` to launch a new app based on a Dockerfile (following the guide [here](https://fly.io/docs/languages-and-frameworks/dockerfile/)). I accidentally had a bug in my dockerfile so it failed to build (error log 1).

I eventually fixed the build and tried to run `flyctl launch` to continue, but it kept erroring saying I must provide an organization or app ID (error log 2). Even passing one with `-a $name` did not make anything work. I was quite stuck for a while until I realized I could just `flyctl deploy` and have it do the right thing.

Would it be possible to make `flyctl launch` somehow detect this state and ask the user to run `flyctl deploy`?

* Operating system: WSL2 (5.15.68.1-microsoft-standard-WSL2)
* `fly version`: flyctl v0.0.429 linux/amd64 Commit: 6db701e0 BuildDate: 2022-11-04T13:51:06Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for khel on 2022-11-09T16:22:11-08:00

app = "khel"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8088
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

Error log 1:

```text
.... trimmed ....
#22 87.26     = note: source type: `SocketAddrV4` (48 bits)
#22 87.26     = note: target type: `sockaddr_in` (128 bits)
#22 87.26
#22 87.28    Compiling serde v1.0.115
#22 87.29 For more information about this error, try `rustc --explain E0512`.
#22 87.29 error: could not compile `socket2` due to previous error
#22 87.29 warning: build failed, waiting for other jobs to finish...
------
Error failed to fetch an image or build from source: error building: executor failed running [/bin/sh -c cargo build --release]: exit code: 101
```

Error log 2:

```text
➜  khel git:(master) ✗ fly launch
An existing fly.toml file was found for app khel
App is not running, deploy...
==> Building image
WARN Failed to start remote builder heartbeat: must provide either an organization id or app name
WARN failed to create build in graphql: input:3: createBuild Could not find App

Error failed to fetch an image or build from source: error connecting to docker: must provide either an organization id or app name
```
