### ISSUE TITLE
Cannot Deploy using Gitlab CI

### ISSUE THREAD

**Issue by allenwyma** [superfly/flyctl#1579]
**Describe the bug**
Briefly, describe what broke and provide the following details:

* Operating system
gitlab CI builder:
```yaml
deploy:
  image: flyio/flyctl
  stage: deploy
  environment:
    name: staging
    url: https://xxx.fly.dev
  script:
    - flyctl deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
```
** Paste your `fly.toml`

```toml
# fly.toml file generated for marge on 2022-12-26T15:56:12+08:00

app = "xxx"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "xxx.fly.dev"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
Using docker image sha256:f9caeeede451e17679ebb3f94d4a408e4c3cd6b6870c067d6c1546fa26ea91a1 for flyio/flyctl with digest flyio/flyctl@sha256:48fe668d240fede8fcdbb21b6cfed3511084335e3914278a3da35ceeb30e8190 ...
Error: unknown command "sh" for "flyctl"
Did you mean this?
	ssh
	vm
Run 'flyctl --help' for usage.
Error unknown command "sh" for "flyctl"
Did you mean this?
	ssh
	vm
```
