### ISSUE TITLE
Apps v2: "no processes defined with that name"

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1594]
Just checking the latest behaviour tonight. Followed the nginx steps from the forum announcements. Got this error (https://github.com/superfly/flyctl/blob/appsv2/internal/app/app.go#L856) on deploy with the starter `fly.toml`: 

```
--> Verified app config
Error error service specifies 'app' as one of its processes, but no processes are defined with that name; update fly.toml [processes] to include a app process
```

* `fly version`
fly v0.0.451-pre-3 darwin/arm64

**fly.toml**
```toml
# fly.toml file generated for this on 2023-01-18T19:29:17-05:00

app = "this"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "nginx"

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```
