### ISSUE TITLE
Apps v2: should `fly.toml` be generated with `[experimental]` or `grace_period` at launch?

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1621]
`fly launch` generates  a `fly.toml` with 

```toml
[experimental]
  auto_rollback = true
```
 
and 

```toml
[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

We can point out in docs that `[experimental]` and `grace_period` aren't supported, but it would be nice if new configs only had settings we support.
