### ISSUE TITLE
Deployment silently fails with malformed fly.toml

### ISSUE THREAD

**Issue by Plecra** [superfly/flyctl#1635]
**Describe the bug**
With a duplicated service (I'm guessing it's the overlapping port?), deployment fails with a HTTP 504 and no details.

* Operating system
flyctl.exe v0.0.450 windows/amd64 Commit: 51325e4a BuildDate: 2023-01-13T21:57:29Z

```toml
# fly.toml file generated for reddit-assist on 2023-01-27T13:19:32Z

app = "reddit-assist"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["docker.io/paketocommunity/rust"]

[mounts]
source = "reddit_assist_store"
destination = "/data"
```
