### ISSUE TITLE
flyctl auth whoami returns blank output

### ISSUE THREAD

**Issue by bwhli** [superfly/flyctl#1649]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

Running `fly auth whoami` returns blank output. I've tried other fly auth commands like `fly auth token` and they work fine.

* Operating system: macOS 13.1
* `fly version`: fly v0.0.451 darwin/arm64 Commit: 5a5b5b1f BuildDate: 2023-01-29T16:01:51Z

** Paste your `fly.toml`

```toml
app = "redacted"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 3
    timeout = "10s"  
```

** Command output: **

```text
N/A (output is blank)
```
