### ISSUE TITLE
flyctl apps open says app is not deployed, but it is

### ISSUE THREAD

**Issue by einarpersson** [superfly/flyctl#1666]
**Describe the bug**
I deployed using `superfly/flyctl-actions/setup-flyctl@master` like this
```
      - run: flyctl deploy --remote-only --app ${{ env.DEPLOY_SLUG }} --region ${{ env.REGION }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

It was successful. I can navigate to the URL and see that the service is running. When running `fly apps list`  it is listed there. When going to the Fly dashboard I can find it there, and navigate to the deployed service.
``` 
solitary-violet-1576-add-region-2       personal                running         nomad           5m18s ago
```

**However**, when running `flyctl apps open solitary-violet-1576-add-region-2` I get the following:

```
Error app has not been deployed yet. Please try deploying your app first
```

* Operating system: `Ubuntu 20.04.5 LTS` running in WSL2 (Win10 Pro)
* `fly version`: `flyctl v0.0.451 linux/amd64 Commit: 5a5b5b1f BuildDate: 2023-01-29T21:49:28Z`

** Paste your `fly.toml`

```toml
# fly.toml file generated for solitary-violet-1576 on 2023-02-04T21:05:07+01:00

app = "solitary-violet-1576"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
Error app has not been deployed yet. Please try deploying your app first
```
