### ISSUE TITLE
‘flyctl auth login’ error is shown when deploying application in github actions

### ISSUE THREAD

**Issue by JuzerShakir** [superfly/flyctl#1787]
### Describe the bug
So I want to deploy my ruby on rails application after all the test passes to [fly.io](http://fly.io/), so I followed the instructions in this [document](https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/#:~:text=Run%20flyctl%20launch%20to%20create,and%20N%20to%20immediate%20deployment.&text=Commit%20your%20changes%20and%20push%20them%20up%20to%20GitHub.) but it doesn’t seem to work. 

I receive this error message `No access token available. Please login with 'flyctl auth login'

Fly version:  `flyctl 0.0.470`

### My `fly.toml` file

```toml
# fly.toml file generated for fmb on 2023-01-01T23:25:36+05:30

app = "fmb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:server"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

```

** Command output: **

Here’s the error received by github-actions:

```
Run flyctl deploy --remote-only
  
Error No access token available. Please login with 'flyctl auth login'

Error: Process completed with exit code 1.
```

I have already setup FLY_API_TOKEN in my github secrets.
