### ISSUE TITLE
Fly deploy fails to mount volume on the second deploy

### ISSUE THREAD

**Issue by jeregrine** [superfly/flyctl#1815]
I'm testing out some changes for machines and statics, as well as the new feature of serving statics from volumes. I have a test repo that exercises this and the new fly.toml [here](https://github.com/jeregrine/statics_test). (**Note** this fly.toml will error as it found a bug, but if you remove the app-static it will work)

## Steps
1. `fly apps create m-statics --machine`
2. `fly vol create data`
3. `fly deploy` 

All good, site works, on next `fly deploy` I get this

```shell
..
deployment-01GTHW5G6CHQEPJ659000MHQA3: digest: sha256:db5bd1d2add39460f70db3fd2f974483bd8cbea1f8879ffc292f9b3e0cf56a6f size: 2833
--> Pushing image done
image: registry.fly.io/m-statics:deployment-01GTHW5G6CHQEPJ659000MHQA3
image size: 510 MB
Error error machine e784ee79f60283 does not have a volume configured and fly.toml expects one with destination /data; remove the [mounts] configuration in fly.toml or use the machines API to add a volume to this machine
```

If I destroy the machine, and `fly deploy` it works again. I would expect the `fly deploy` to work every time. 

* `fly v0.0.474 darwin/arm64 Commit: dc3a37a7 BuildDate: 2023-03-01T23:27:43Z`

** Paste your `fly.toml`

```toml
app = "m-statics"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]

[env]
  PHX_HOST = "kyle-please.fly.dev"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/app-static"

[[statics]]
  guest_path = "/data"
  url_prefix = "/vol-static"

[mounts]
  source = "data"
  destination = "/data"
```
