### ISSUE TITLE
Apps v2 -`fly services list` doesn't show services after cloning a Machine

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1838]
This might have something to do with process groups too?

To reproduce:

```
$ fly launch --image nginx --force-machines
...
? Would you like to deploy now? Yes
==> Building image
Searching for image 'nginx' remotely...
image found: img_e1zd4mkn80yp02yw
Provisioning ips for gah
  Dedicated ipv6: 2a09:8280:1::f553
  Shared ipv4: 66.241.125.38
  Add a dedicated ipv4 with: fly ips allocate-v4
No machines in gah app, launching one new machine
  Machine 3d8d9900ce2289 [app] update finished: success
  Finished deploying

```

Check the status; health check is passing
```
$ fly status
App
  Name     = gah                   
  Owner    = personal              
  Hostname = gah.fly.dev           
  Image    = library/nginx:latest  
  Platform = machines              

Machines
ID              PROCESS VERSION REGION  STATE   HEALTH CHECKS           LAST UPDATED         
3d8d9900ce2289  app     1       yyz     started 1 total, 1 passing      2023-03-07T01:14:56Z
```
`fly services list` is fine:

```
$ fly services list
Services
PROTOCOL        PORTS                   FORCE HTTPS 
TCP             80 => 80 [HTTP]         True       
                443 => 80 [TLS,HTTP]    False      
```

Add some process groups to config:

```
[processes]
  app = ""
  web = "nginx -g 'daemon off;'"
  worker = "tail -F /dev/null"
```

(I got an error trying to deploy without adding the `"app"` line to `fly.toml`)

Clone the machine to one of the process groups            
```
$ fly machine clone --process-group web 3d8d9900ce2289
Cloning machine 3d8d9900ce2289 into region yyz
INFO Setting process group to web for new machine and updating cmd, services, and checks
Provisioning a new machine with image registry-1.docker.io/library/nginx:latest@sha256:942ae2dfd73088b54d7151a3c3fd5af038a51c50029bfcfd21f1e650d9579967...
  Machine 4d891de2f6e587 has been created...
  Waiting for machine 4d891de2f6e587 to start...
No health checks found
Machine has been successfully cloned!
```

Now check on services again:
```
$ fly services list                                   
Services
PROTOCOL        PORTS   FORCE HTTPS 

20:18:13 [~/FlyTests/march2/nginx2]$ 
```

(Services are still actually OK: can visit the app in the browser and `fly status` gives
```
Machines
ID              PROCESS VERSION REGION  STATE   HEALTH CHECKS           LAST UPDATED         
3d8d9900ce2289  app     2       yyz     started 1 total, 1 passing      2023-03-07T01:16:23Z
4d891de2f6e587  web     2       yyz     started                         2023-03-07T01:17:47Z
```
)

**Comment by tvdfly** [comment]
What is the full fly.toml (especially services) after the processes are added?

**Comment by catflydotio** [comment]
```
# fly.toml file generated for gah on 2023-03-06T20:14:49-05:00

app = "gah"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"

[experimental]
  auto_rollback = true

[processes]
  app = ""
  web = "nginx -g 'daemon off;'"
  worker = "tail -F /dev/null"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
```

**Comment by catflydotio** [comment]
Update (I'm now on flyctl v0.0.492): if I launch a new app from a `fly.toml` with one process group, `web`, defined (and the services set up accordingly), `fly services list` shows the services.

If I launch with two process groups, `web`, and `worker`, `fly services list` shows no services. 

The only difference is one line in `fly.toml`.

(in both cases the app is reachable via the browser)

Here's `fly.toml` with both process group lines. Delete the `worker` line to get the other `fly.toml`.

```toml
# fly.toml file generated for gpha on 2023-03-19T17:51:13-04:00

app = "gpha"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"

[experimental]
  auto_rollback = true

[build]
  image = "nginx"

[processes]
  web = ""
  worker = "tail -F /dev/null"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
```
