### ISSUE TITLE
Suggested http check config causes error on deploy

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#207]
I have an app with this as the config, it worked until 5 days ago (I think):

```toml
[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [service.http_checks.headers]
      Host = "health.check"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
```

When I deploy, this happens:
```
➜  ui git:(master) ✗ flyctl deploy
Deploying flyio-ui
==> Validating App Configuration
Oops, something went wrong! Could you try that again?
```

If I change the config to this it works just fine:

```toml
[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    handlers = ["tls","http"]
    port = "443"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/status"
    protocol = "http"
    timeout = 2000
    headers = { Host = "health.check" }
```
