### ISSUE TITLE
`fly deploy` should clear `standby-for` when services are added to a process

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#2162]
If a process group has no service on launch, it gets a standby machine. If I add a service to that process and `fly deploy`, I end up with a machine with a service _and_ the standby label.

To reproduce:

Launch an app with no services
e.g.

```toml
app = "floof"
primary_region = "yyz"

[build]
  image = "nginx"

[processes]
  aab = ""
  worker = "tail -F /dev/null"
```

```
$ fly launch
...
$ fly status
PROCESS ID              VERSION REGION  STATE   CHECKS  LAST UPDATED         
aab     9e784e26c07183  1       yyz     started         2023-04-22T22:34:45Z
aab†    17811122f01789  1       yyz     stopped         2023-04-22T22:34:47Z
worker  4d891deec57087  1       yyz     started         2023-04-22T22:34:47Z
worker† 178116d0fe9089  1       yyz     stopped         2023-04-22T22:34:49Z
```
Now edit `fly.toml`:

```toml

app = "floof"
primary_region = "yyz"

[build]
  image = "nginx"

[processes]
  aab = ""
  worker = "tail -F /dev/null"

[http_service]
  processes = ["aab"]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "3s"
    timeout = "2s"
    grace_period = "5s"
```

Deploy again and see a standby machine with a health check:

```
$ fly deploy
$ fly status
...
Machines
PROCESS ID              VERSION REGION  STATE   CHECKS                  LAST UPDATED         
aab     9e784e26c07183  2       yyz     started 1 total, 1 passing      2023-04-22T22:37:27Z
aab†    17811122f01789  2       yyz     stopped 1 total                 2023-04-22T22:37:21Z
worker  4d891deec57087  2       yyz     started                         2023-04-22T22:37:24Z
worker† 178116d0fe9089  2       yyz     stopped                         2023-04-22T22:37:21Z
```
