### ISSUE TITLE
migrate-to-v2 fails with unmarshal error

### ISSUE THREAD

**Issue by byronwilliams** [superfly/flyctl#2291]
**Describe the bug**
When trying to migrate to v2 I get the following error:

```
$ fly migrate-to-v2

   ✘json: cannot unmarshal number into Go struct field ServiceHTTPCheck.services.http_checks.headers of type string

Error: failed to validate config for Apps V2 platform: App configuration is not valid
```

This doesn't seem to actually be coming from the toml file, as if I delete the sections the error continues

* Operating system
* `fly version`
```
$ fly version
flyctl v0.1.6 linux/amd64 Commit: da96e6137f55f8fdcf26aa3d3b547c89c2958a2c BuildDate: 2023-05-16T19:36:36Z
```

** Paste your `fly.toml`

```toml
app = "my-app-name-here"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200


[[services]]
  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    [services.http_checks.headers]



  internal_port = 8080
  processes = ["app"]
  # protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 150
    soft_limit = 100
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

 # [[services.tcp_checks]]
 #   grace_period = "1s"
 #   interval = "15s"
 #   restart_limit = 0
 #   timeout = "2s"

```

** Command output: **

```text

   ✘json: cannot unmarshal number into Go struct field ServiceHTTPCheck.services.http_checks.headers of type string

Error: failed to validate config for Apps V2 platform: App configuration is not valid
```
