### ISSUE TITLE
[Node] `Flyctl launch` runs "prepare" of dependencies package.json

### ISSUE THREAD

**Issue by ben-xD** [superfly/flyctl#2314]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your 
application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
When running `flyctl launch`, a dependency's `prepare` npm run script is called. In this case, I have a dependency called `zod`, which has a `package.json` containing `"prepare": "husky install"`. There is no need to run this, I don't use husky and don't want it to run. My application builds fine without flyctl.

* Operating system
* `fly version`
```
fly v0.1.8 darwin/arm64 Commit: 8c7a3494a027b7ebfe503a516d0080c5ef8080e1-dirty BuildDate: 2023-05-18T17:25:09Z
```

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for password-hasher on 2023-05-20T10:52:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "password-hasher"
primary_region = "lhr"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0

[env]
HUSKY = 0
PORT = 3000
```

** Command output: **

```text
$ fly launch                       ✔  11:07:42 AM 
Creating app in /Users/zen/repos/batmark/password-hasher
An existing fly.toml file was found for app password-hasher
? Would you like to copy its configuration to the new app? Yes
Scanning source code
Detected a NodeJS app
? Choose an app name (leaving blank will default to 'password-hasher') 
? App password-hasher already exists, do you want to launch into that app? Yes
App will use 'lhr' region as primary

Admin URL: https://fly.io/apps/password-hasher
Hostname: password-hasher.fly.dev
? Would you like to set up a Postgresql database now? No
? Would you like to set up an Upstash Redis database now? No
npm ERR! code 1
npm ERR! path /Users/zen/repos/batmark/node_modules/.pnpm/zod@3.21.4/node_modules/zod
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zen/.npm/_logs/2023-05-20T09_07_49_561Z-debug-0.log
Error: failed to install @flydotio/dockerfile: exit status 1
```
