### ISSUE TITLE
`fly deploy -i my_image:latest --local-only` fails on macOS

### ISSUE THREAD

**Issue by peredwardsson** [superfly/flyctl#2331]
**Describe the bug**
Trying to deploy a Docker image via fly using my local image. The command I'm running is ` fly deploy --local-only -i my_image:latest`

* Operating system
macOS 13.3.1
* `fly version`
`fly v0.1.12 darwin/arm64 Commit: b0911e043fbfb315d5a924d7f3ad4ed673967a22-dirty BuildDate: 2023-05-24T01:54:16Z`
** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for redacted on 2023-05-24T08:33:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redacted"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "arn"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
```

** Command output: **

```text
==> Verifying app config
Validating <path>/fly.toml
Platform: machines
✓ Configuration is valid
--> Verified app config
==> Building image
WARN failed to create build in graphql: input:3: createBuild Could not find App

Error: failed to fetch an image or build from source: no docker daemon available
```

Docker is totally running. I can build the image, for instance, using `docker build...`. 
```
❱ docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.16.0 (94771)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Remote building works, so I suspect the problem is located on my machine somewhere, and probably not on the Dockerfile or the app itself. Any other data I can provide?
