### ISSUE TITLE
Error Postgres Flyctl fly postgres attach 

### ISSUE THREAD

**Issue by bogordesaincom** [superfly/flyctl#2367]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Error Postgres Flyctl fly postgres attach command 
failed retrieving postgres app `pgapp` ( example ): Field 'limitedAccessTokens' doesn't exist on type 'App'
* Operating system
```
fly v0.1.21 darwin/arm64 Commit: 727187f143dd6636ba2e6ecdd4675260fc511b82 BuildDate: 2023-05-29T21:48:55Z
```
** Paste your `fly.toml`

```toml
app = "api-perdoki"
primary_region = "sin"
# console_command = "php /var/www/html/artisan tinker"

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:work --sleep=3 --tries=3 --backoff=3 --max-time=3600"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.0"
    PHP_DATE_TIMEZONE="Asia/Jakarta"


[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  # processes = ["app"]
  source="production_storage"
  destination="/var/www/html/storage/app"
```

** Command output: **

```text
failed retrieving postgres app `pgapp` ( example ): Field 'limitedAccessTokens' doesn't exist on type 'App'

```
