### ISSUE TITLE
`fly launch` creates failing health checks for Rails 7.1 apps

### ISSUE THREAD

**Issue by nreilly** [superfly/flyctl#2475]
**The bug**
Fly launch creates health checks for the new Rails 7.1 discoverable health checks as shown [here](https://fly.io/ruby-dispatch/health-checks/). However, the checks generated will fail as the default Rails configuration forces https.

 I've tested with both the homebrew flavour of flyctl, and a fresh build.

By adding  `X-Forwarded-Proto = "https"` to the generated check in the `fly.toml`, we can get it to pass.

* `14.0 Beta (23A5276g)`
* `fly v0.1.40 darwin/amd64 Commit: e66f5f35e30a886c4572639197c28db58046effa-dirty BuildDate: 2023-06-21T17:47:00Z`
* `flyctl v0.0.0-1687485852+dev darwin/amd64 Commit: 620a4fc1eea7737eae58e607444aad448655b8bc BuildDate: 2023-06-23T02:04:12Z BranchName: master`
* `Rails 7.1.0.alpha`

**Generated `fly.toml`**
```toml
app = "hc"
primary_region = "syd"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]  
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
```

**Status Check:**
```text
  NAME   | STATUS   | MACHINE        | LAST UPDATED | OUTPUT                 
---------*----------*----------------*--------------*------------------------
  status | critical | 3d8d9902f0e268 | 48s ago      | 301 Moved Permanently  
---------*----------*----------------*--------------*------------------------
```

**Adjusted `fly.toml`**
```toml
app = "hc"
primary_region = "syd"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]  
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    [checks.status.headers]
      X-Forwarded-Proto = "https"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
```

**Resulting Status Check:**
```text
  NAME   | STATUS  | MACHINE        | LAST UPDATED | OUTPUT                                                      
---------*---------*----------------*--------------*-------------------------------------------------------------
  status | passing | 3d8d9902f0e268 | 3s ago       | <html><body style="background-color: green"></body></html>  
---------*---------*----------------*--------------*-------------------------------------------------------------
```

**Comment by nreilly** [comment]
The linked pull request resolves the issue
```
  NAME   | STATUS  | MACHINE        | LAST UPDATED | OUTPUT                                                      
---------*---------*----------------*--------------*-------------------------------------------------------------
  status | passing | 3287314b032685 | just now     | <html><body style="background-color: green"></body></html>  
---------*---------*----------------*--------------*-------------------------------------------------------------
```
Using `flyctl v0.0.0-1687908539+dev darwin/amd64 Commit: 313f950616cdab01d9ba4adf46d363a4d4137613 BuildDate: 2023-06-27T23:28:59Z BranchName: rails-health-https`

Extract from fly.toml:
``` toml
[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    [checks.status.headers]
      X-Forwarded-Proto = "https"
```
