### ISSUE TITLE
`fly certs show` doesn't give details of AAAA record. Unable to issue a certificate

### ISSUE THREAD

**Issue by theobile** [superfly/flyctl#2477]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:
Trying to obtain certificates for my custom domain. CLI asks me to add an AAAA record but doesn't prvide any address. Response trails. `fly certs show totspot.ca`

* Operating system 
MacOS Monterey

* `fly version`
fly v0.1.40 darwin/amd64 Commit: e66f5f35e30a886c4572639197c28db58046effa-dirty BuildDate: 2023-06-21T17:47:00Z

** Paste your `fly.toml`

```toml

app = "totspot"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8080"
METRICS_PORT = "8081"

[metrics]
port = 8_081
path = "/metrics"

[deploy]
release_command = "npx prisma migrate deploy"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8_080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/healthcheck"
protocol = "http"
timeout = "2s"
tls_skip_verify = false
headers = {}

```

** Command output: **

```text
The certificate for totspot.ca has not been issued yet.

Hostname                  = totspot.ca
DNS Provider              = whc
Certificate Authority     = Let's Encrypt
Issued                    =
Added to App              = 1 hour ago
Source                    = fly
You are creating a certificate for totspot.ca
We are using lets_encrypt for this certificate.

You can validate your ownership of totspot.ca by:

1: Adding an AAAA record to your DNS service which reads:

    AAAA @
```
