### ISSUE TITLE
flyctl accepts service with no internal port or protocol

### ISSUE THREAD

**Issue by jvns** [superfly/flyctl#2521]
**Describe the bug**

This is more of a usability issue -- I accidentally tried to set concurrency settings in `[services.concurrency]` instead of `[http_service.concurrency]`, and the result was that flyctl configured a service with these parameters:

```
    {
      "concurrency": {
        "type": "connections",
        "hard_limit": 500,
        "soft_limit": 500
      },
      "force_instance_key": null
    }
``` 

I was surprised that flyctl accepted a service with no `protocol` or `internal_port` set -- I'd expect this configuration to be rejected because it's missing required fields.

Fly version: fly v0.1.46 darwin/arm64

** Paste your `fly.toml`

```toml
app = "linux-playground"
primary_region = "yul"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services.concurrency]
  type = "connections"
  hard_limit = 500
  soft_limit = 500
```
