### ISSUE TITLE
Updating machine size removes concurrency settings

### ISSUE THREAD

**Issue by korbin** [superfly/flyctl#2611]
**Describe the bug**
When using `fly machine update --size <plan>`, concurrency settings are removed from the machine configuration (similar to https://github.com/superfly/flyctl/pull/2288)

```flyctl v0.1.64 linux/amd64 Commit: 1ddff4ccdd97ca10913306db4733c1d486b38209 BuildDate: 2023-07-21T22:23:46Z```

```toml
[build]
dockerfile = "Dockerfile"
context = ".."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "connections"
  hard_limit = 500
  soft_limit = 250

[services.concurrency]
  type = "connections"
  hard_limit = 500
  soft_limit = 250
```
