### ISSUE TITLE
Cant create multiple volumes mounts for single app

### ISSUE THREAD

**Issue by evereq** [superfly/flyctl#2625]
**Describe the bug**

Creating multiple mounts failing, while I do see some references that it seems possible in other GitHub issues with [[mounts]] to be included a few times in the `fly.toml` file.

* Operating system 

Windows

* `fly version`

v0.1.65

** Paste your `fly.toml`

```toml

[[mounts]]
  source = "api_data"
  destination = "/srv/gauzy/apps/api/data"
  processes= ["app"]

[[mounts]]
  source = "api_public"
  destination = "/srv/gauzy/apps/api/public"
  processes= ["app"]

```

** Command output: **

```text
Error: failed loading app config from ...: Key 'mounts' was already created and cannot be used as an array.
```
