### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by diamond-fish** [superfly/flyctl#2740]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
I followed [instructions](https://fly.io/docs/hands-on/install-flyctl/) to install the CLI, but I got an error (see command output below). It seems the documentation is missing a step to add the required directory to the PATH (or better if `install.ps1` can do this for us).

* Operating system: Windows 10
* `fly version`:  v0.1.84 windows/amd64 Commit: 5735a8b979ebc938c74832c3edd52c509abaa7eb BuildDate: 2023-08-23T16:56:07Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for python-paas on 2023-02-12T09:57:15-05:00

app = "python-paas"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[build.args]
  BP_CPYTHON_VERSION = "3.10.*"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

** Command output: **

```text
PS C:\WINDOWS\system32> powershell -Command "iwr https://fly.io/install.ps1 -useb | iex"
Downloading flyctl...
flyctl was installed successfully to C:\Users\username\.fly\bin\flyctl.exe
Run 'flyctl --help' to get started
PS C:\WINDOWS\system32> flyctl --help
flyctl : The term 'flyctl' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ flyctl --help
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (flyctl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
