### ISSUE TITLE
--org parameter is ignored

### ISSUE THREAD

**Issue by yanc0** [superfly/flyctl#2746]
**Describe the bug**

--org argument is set but the command is asking for the organization anyway.

* Ubuntu 22.04.3 LTS
* `flyctl v0.1.84 linux/amd64 Commit: 5735a8b979ebc938c74832c3edd52c509abaa7eb BuildDate: 2023-08-23T16:56:07Z`

**Paste your `fly.toml`**

```toml
app = "radicale"
primary_region = "cdg"

[http_service]
  internal_port = 5232
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "radicale_data"
  destination = "/data
```

**Command output:**

```text
$ flyctl ssh issue --agent --org personal
? Select Organization:  [Use arrows to move, type to filter]
> Yann (personal)
  my.org.com (my-org-com)
```
