### ISSUE TITLE
fly deploy is very slow

### ISSUE THREAD

**Issue by andrecasal** [superfly/flyctl#2824]
**Describe the bug**
Briefly, describe what broke and provide the following details:

* Operating system: macOS Ventura 13.5.2 (22G91)
* `fly version`: fly v0.1.92 darwin/amd64 Commit: f8e5cccff1f16869d16ad2f8b95f4a396ec771b7-dirty BuildDate: 2023-09-12T22:46:51Z

** Paste your `fly.toml`

```toml
app = "andrecasal-com"
primary_region = "mad"
kill_signal = "SIGINT"
kill_timeout = 5
processes = [ ]

[experimental]
allowed_public_ports = [ ]
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[deploy]
release_command = "node ./other/sentry-create-release"

[[services]]
internal_port = 8_080
processes = [ "app" ]
protocol = "tcp"
script_checks = [ ]

  [services.concurrency]
  hard_limit = 100
  soft_limit = 80
  type = "connections"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

  [[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/resources/healthcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false
  headers = { }
```

** Command output: **

It's just extremelly slow on the `transferring context: 50.26MB` part.
