### ISSUE TITLE
Feature request: Wider range of service ports

### ISSUE THREAD

**Issue by a-h** [superfly/flyctl#292]
I was trying Fly out today, and wanted to expose port 1965 on the service (the default port of the TCP service), but I had to use port 10000 instead, as per the docs:

> port : A string which selects which external ports you want Fly to accept traffic on. You can configure an application to listen for global traffic on ports 80, 443, 5000, and ports 10000 - 10100.

My configuration looked like this:

```toml
app = "gemini-test-suite"

[[services]]
  internal_port = 1965
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = "10000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
```
