### ISSUE TITLE
Generated env.sh.eex creates RELEASE_NODE value that is invalid

### ISSUE THREAD

**Issue by krainboltgreene** [superfly/flyctl#2995]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details: I built a new fly.io app for my phoenix project but it won't boot or open a remote due to a bad `RELEASE_NODE` name. See https://github.com/superfly/flyctl/commit/b330abd30a9d6fc0ac12c44e2eabd8d046b9184c#diff-38d8fc5cf1c36ebfcf451fc5a53f5a14bb4c2595f0ddb2c324c54f3510cb5981R116

* flyctl v0.1.117 linux/amd64 Commit: 9cbe887990dac7919ba0a95a5dc6e91943b84b57 BuildDate: 2023-11-02T22:13:35Z

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for baldurs-mouth on 2023-11-06T08:30:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "baldurs-mouth"
primary_region = "sea"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "baldurs-mouth.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

```

``` eex
#!/bin/sh

# configure node for distributed erlang with IPV6 support
export ERL_AFLAGS="-proto_dist inet6_tcp"
export ECTO_IPV6="true"
export DNS_CLUSTER_QUERY="${FLY_APP_NAME}.internal"
export RELEASE_DISTRIBUTION="name"
export RELEASE_NODE="${FLY_APP_NAME}-${FLY_IMAGE_REF##*-}@${FLY_PRIVATE_IP}"
```

** Command output: **

```text
Protocol 'inet6_tcp': invalid node name: rem-b29b-baldurs-mouth-baldurs-mouth@sha256:0749a475e4aaa3d045c19be850c082a0bc0c7835327d73303febaefff14b1f4e@fdaa:0:3267:a7b:121:5961:9306:2
```
