### ISSUE TITLE
fly launch is adding stuff to my fly.toml

### ISSUE THREAD

**Issue by boozedog** [superfly/flyctl#3140]
I have a python app with the following `fly.toml`:

```toml
app = "myapp"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  first = "python3 main.py --first"
  second = "python3 main.py --second"
  third = "python3 main.py --third"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["first", "second", "third"]
```

I am trying to launch (but not deploy) the app using this command:

```sh
fly launch --name myapp --org myorg --region lax --copy-config --no-deploy
```

When I do that, my `fly.toml` gets automatically updated to add the following:

```toml
[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
```

But I don't need or want an http service or any inbound connectivity.

And in any case, it doesn't launch, it errors out with following message:

```txt
Wrote config file fly.toml
Validating fly.toml
Platform: machines
Service specifies 'app' as one of its processes, but no processes are defined with that name; update fly.toml [processes] to add 'app' process or remove it from service's processes list

   ✘invalid app configuration
Error: invalid configuration file: App configuration is not valid
```

Any ideas? Thanks!
