### ISSUE TITLE
fly deploy failed with Error: found 2 machines that are unmanaged

### ISSUE THREAD

**Issue by carlwilk32** [superfly/flyctl#3149]
**Describe the bug**
fly deploy failed when running github action with fly.io deploy.
Both machines use platform v2.
details: https://github.com/carlwilk32/ktor-github-package-registry-proxy/actions/runs/7393603459/job/20113772559

NOTE: restart of action did finish successfully. 

* Operating system: Ubuntu 22.04.3 LTS
* `fly version`:  flyctl 0.1.136 is installed

**Paste your `fly.toml`**

```toml
app = "ktor-github-package-registry-proxy"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
```

**Command output:**

```text
Error: found 2 machines that are unmanaged. `fly deploy` only updates machines with fly_platform_version=v2 in their metadata. Use `fly machine list` to list machines and `fly machine update --metadata fly_platform_version=v2 <machine id>` to update individual machines with the metadata. Once done, `fly deploy` will update machines with the metadata based on your fly.toml app configuration
Error: Process completed with exit code 1.
```
