### ISSUE TITLE
`fly console` crashes when the key `[[vm]] memory = "1gb"` is set

### ISSUE THREAD

**Issue by bradgessler** [superfly/flyctl#3203]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

This works as expected:

```toml
[[vm]]
  size = "shared-cpu-1x"
  memory_mb = 1024
  processes = ["console"]
```

But this does not:

```toml
[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  processes = ["console"]
```

```bash
$ fly console -C 'printenv FLY_VM_MEMORY_MB'
Oops, something went wrong! Could you try that again?
```

* Operating system

macOS 14.3

* `fly version`

```bash
$ fly version
fly v0.1.143 darwin/arm64 Commit: 6d5058a4bc9359d19288fb9f066cd495d00c1d6e-dirty BuildDate: 2024-01-16T19:28:48Z
```

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for tinyzap on 2023-08-01T01:22:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "myapp"
primary_region = "sjc"
console_command = "/rails/bin/rails console"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  processes = ["console"]

[env]
  LINK_ALIAS_HOST = "tinyzap.co"
  CANONICAL_HOST = "tinyzap.com"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[services]]
  processes = ["worker"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[processes]
  app = "bin/rails server"
  worker = "bin/good_job start"
```
