### ISSUE TITLE
`fly postgres connect` broken

### ISSUE THREAD

**Issue by owenthereal** [superfly/flyctl#3313]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

`fly postgres connect` is broken for a [postgres-flex](https://github.com/fly-apps/postgres-flex) image

* Operating system: macos
* fly version
fly v0.2.9 darwin/arm64 Commit: 3fbcdb941df8e5e46a3d11a85404004b86e91dd3-dirty BuildDate: 2024-02-19T16:54:19Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for shaun-flex-stable-3 on 2023-01-24T10:42:59-06:00


kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PRIMARY_REGION = "ord"

[checks]
  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"

[[mounts]]
  destination = "/data"
  source = "pg_data"

[metrics]
  path = "/metrics"
  port = 9187

```

** Command output: **

```text
fly postgres connect -a MYAPP --debug --verbose
Error: Malformed version: ustom
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/superfly/flyctl/internal/cli.printError(0x1400051c000, 0x14000c8fb76, 0x14000c00308, {0x106d49318, 0x14000b86a00})
	github.com/superfly/flyctl/internal/cli/cli.go:162 +0x3c8
github.com/superfly/flyctl/internal/cli.Run({0x106d65770?, 0x140002e7e80?}, 0x1400051c000, {0x1400004c240, 0x6, 0x6})
	github.com/superfly/flyctl/internal/cli/cli.go:110 +0x7fc
main.run()
	github.com/superfly/flyctl/main.go:47 +0x174
main.main()
	github.com/superfly/flyctl/main.go:26 +0x20
```
