### ISSUE TITLE
Flyctl stopped working 

### ISSUE THREAD

**Issue by boriskogan81** [superfly/flyctl#3333]
**Describe the bug**
I have an app deployed and running. I was using flyctl with no issues. I came back after about a week and attempted to run `fly deploy` and got this error message:

> Program ‘fly.exe’ failed to run: Access is deniedAt line:1 char:1
> 
> fly deploy
> At line:1 char:1
> 
> fly deploy
>   + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
>   + FullyQualifiedErrorId : NativeCommandFailed

I am running this on a Windows machine, have tried with administrator Powershell, have tried updating flyctl via `pwsh -Command "iwr https://fly.io/install.ps1 -useb | iex"` and restarting my machine. I have checked my PATH and C:\Users\%USER%\.fly\bin is in there.

* Operating system

Windows 10

* `fly version`

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for ofanymfrontend on 2024-02-05T17:28:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ofanymfrontend'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
```
