### ISSUE TITLE
Turn of AWS_ACCESS_KEY_ID warning

### ISSUE THREAD

**Issue by ananthb** [superfly/flyctl#3375]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
flyctl flags the `AWS_ACCESS_KEY_ID` environment variable as being "potentially sensitive". AWS' stance on this is that this variable is not a secret. It is even publicly displayed in pre-signed URLs and such.

I understand the consequences of using it in an env var. How can I turn off the warning?

* Operating system
* `fly version`

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for futura-physio-odoo on 2024-01-08T21:25:34+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "futura-physio-odoo"
primary_region = "sin"

[build]
  dockerfile = "Containerfile"

[env]
  HOST = "mudumalai-db.flycast"
  USER = "futura_physio_odoo"
  ODOO_SESSION_REDIS = "true"
  ODOO_SESSION_REDIS_PREFIX = "fp"
  AWS_HOST = "https://59b9363d35105560f2df047c995be5a2.r2.cloudflarestorage.com"
  AWS_ACCESS_KEY_ID = "94288051d6e720130510c946990f1dd1"
  AWS_BUCKETNAME = "futuraphysio-odoo-data"

[[services]]
  internal_port = 8069
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    [services.ports.http_options.response.headers]
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
      Content-Security-Policy = "upgrade-insecure-requests"

[mounts]
  source = "odoo_data"
  destination = "/var/lib/odoo"

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 1024
```

** Command output: **

```text
ananth.b@ananthbs-MacBook-Pro ~/s/m/f/p/futura-physio-odoo (main) [1]> fly deploy
==> Verifying app config
Validating /Users/ananth.b/src/me/fly-apps/personal/futura-physio-odoo/fly.toml
✓ Configuration is valid
--> Verified app config
WARN AWS_ACCESS_KEY_ID may be a potentially sensitive environment variable. Consider setting it as a secret, and removing it from the [env] section: https://fly.io/docs/reference/secrets/
```
