### ISSUE TITLE
Mixing `services.http_checks` with an `http_service` (and vice versa?) results in failing health checks 

### ISSUE THREAD

**Issue by kylemclaren** [superfly/flyctl#3675]
**Describe the bug**
Mistakenly mixing `services.http_checks` with an `http_service` (and possible vice versa, though I haven't tested) results in failing heath checks and therefore failing deployments.

`fly config validate` (and by extension, `fly deploy`) should check for this and fail gracefully.

```toml
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"
```
