### ISSUE TITLE
`--attach` generates a toml with an odd structure

### ISSUE THREAD

**Issue by fliepeltje** [superfly/flyctl#3801]
**Describe the bug**

When I use the `--atach` flag, this is the `fly.toml` that I get in my `fly/apps/<app-name>/fly.toml`

```toml
[experimental]
  [experimental.attached]
    [experimental.attached.secrets]
      [experimental.attached.secrets.export]
        SANDWICH_CHAT_URL = 'http://${FLYCAST_URL}/sandwich-chat'
```

The relevant section of the original `fly.toml` for the attached app looks like this:

```toml
[experimental.attached.secrets.export]
  SANDWICH_CHAT_URL = "http://${FLYCAST_URL}/sandwich-chat"
```

Functionally this of course works, but it looks a bit weird.
