### ISSUE TITLE
deploy uses Dockerfile when present, even with buildpack configured

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#383]
The Papercups repo has a Dockerfile, if I configure fly.toml like this: 

```toml
[build]
  builder = "heroku/buildpacks:18"
  buildpacks = ["https://cnb-shim.herokuapp.com/v1/hashnuke/elixir"]
```

Then run `flyctl deploy`, it uses the Dockerfile instead of the buildpack.
