### ISSUE TITLE
can't deploy when image is configured in the config

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#384]
```toml
app = "ghost-blog"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
image = "ghost:4.1.2"
```

`flyctl deploy` gives me this error:

```
Error app does not have a Dockerfile or buildpacks configured. See https://fly.io/docs/reference/configuration/#the-build-section
```
