### ISSUE TITLE
Fly DB instance has stopped working and I have been trying to restart but it is not getting restarted

### ISSUE THREAD

**Issue by bharatb-futurism** [superfly/flyctl#3917]
*I have found in production logs that roboart-db instance is not running.
Please see the logs below:

**Describe the bug**

 
roboart-db
ID                           NAME                   STATE  CHECKS              REGION               ROLE                                    IMAGE                                             IP ADDRESS                     VOLUME                             CREATED                            LAST UPDATED                PROCESS GROUP                SIZE                 
080e077f915d78            bold-flower-9639            started 2/3         ord         zombie                                 flyio/postgres-flex:15.3 (v0.0.46)           fdaa:5:8cb9:a7b:193:7f7c:71ab:2         vol_149592q3og9l6x3v                2024-01-23T00:57:00Z   2024-09-03T14:32:41Z                shared-cpu-2x:4096MB              
7815107a91e728           lively-snowflake-5683  started 2/3         ord         zombie                                 flyio/postgres-flex:15.3 (v0.0.46)           fdaa:5:8cb9:a7b:17a:d54a:6a69:2        vol_vg7973m6qqod66jv              2024-09-03T13:55:57Z   2024-09-03T14:11:47Z                shared-cpu-2x:4096MB              
7811005f1d7768            white-sound-9475         stopped               0/3         ord         the machine hasn't started                flyio/postgres-flex:15.3 (v0.0.46)            fdaa:5:8cb9:a7b:110:744e:3d83:2        vol_krkdmolmwnn02ky4                2024-01-23T00:57:33Z 2024-09-05T10:30:30Z
 
vol_vg7973m6qqod66jv             2024-09-03T13:55:57Z 2024-09-03T14:11:47Z                shared-cpu-2x:4096MB               
7811005f1d7768            white-sound-9475         stopped               0/3         ord         the machine hasn't started                flyio/postgres-flex:15.3 (v0.0.46)            fdaa:5:8cb9:a7b:110:744e:3

* Operating system : Mac
* `fly version`: fly v0.2.125 darwin/amd64 Commit: 19c7e647cdb47a0673e1e523d6445651961a5a84 BuildDate: 2024-09-02T14:23:40Z

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for roboart-stage on 2023-07-28T07:11:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roboart"
primary_region = "sea"
kill_signal = "SIGTERM"
swap_size_mb = 2048

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "roboart.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

```

** flyctl machines restart 7811005f1d7768 -a roboart-db: **

```text
Restarting machine 7811005f1d7768
Error: failed to restart machine 7811005f1d7768: could not stop machine 7811005f1d7768: failed to restart VM 7811005f1d7768: failed_precondition: machine still active, refusing to start (Request ID: 01J70V8DHQ1ZHSGXD9Y4ZC8XQT-bom)
```
