### ISSUE TITLE
Error launching a new ruby app "helloruby" with ruby 2.7.3

### ISSUE THREAD

**Issue by rcoproc** [superfly/flyctl#396]
When I run flyctl launch(in a ruby app) I have this error:

```
Installing bundler 2.1.4
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rack
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.7.3.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
 Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.7.3.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3

!
 !     The Ruby version you are trying to install does not exist on this stack.
 !     
 !     You are trying to install ruby-2.7.3 on heroku-20.
 !     
 !     Ruby ruby-2.7.3 is present on the following stacks:
 !     
 !     - heroku-16
 !     - heroku-18
 !     - heroku-20
 !     
 !     Heroku recommends you use the latest supported Ruby version listed here:
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     
 !     For more information on syntax for declaring a Ruby version see:
 !     https://devcenter.heroku.com/articles/ruby-versions
 !

```

** Add `fly.toml`

```toml
# fly.toml file generated for young-hill-5978 on 2021-04-10T03:05:43-03:00

app = "young-hill-5978"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"

```

** Command output: **
Gemfile
```text
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
ruby "2.7.3"

gem "sinatra", "~> 2.1"

```

# Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    mustermann (1.1.1)
      ruby2_keywords (~> 0.0.1)
    rack (2.2.3)
    rack-protection (2.1.0)
      rack
    ruby2_keywords (0.0.4)
    sinatra (2.1.0)
      mustermann (~> 1.0)
      rack (~> 2.2)
      rack-protection (= 2.1.0)
      tilt (~> 2.0)
    tilt (2.0.10)

PLATFORMS
  ruby

DEPENDENCIES
  sinatra (~> 2.1)

BUNDLED WITH
   2.1.4

```
