### ISSUE TITLE
Error: failed ensuring config directory perms

### ISSUE THREAD

**Issue by miikaah** [superfly/flyctl#3989]
**Describe the bug**
Nothing works with flyctl anymore. It gives the same error "Error: failed ensuring config directory perms" for everything. I am making this issue because I could not find anything pertinent related to this. The only thing that happened was that I tried to deploy last week and flyctl updated itself to 0.3.14 automatically and then started failing. I guess there is a high likelyhood that this is MacOS related because it no longer shows the prompt that says something like "Allow flyctl to access .fly folder ..." which would explain why it says "operation not permitted". However nothing seems to be able to restore expected behavior.

So far I have tried giving flyctl full disk access and I've restarted the computer. Still no luck. I have uninstalled flyctl and reinstalled it. Nope. I have deleted the .fly folder, no chance. I've tried resetting the permissions for prompts with `tccutil reset All com.googlecode.iterm2`, still no prompts. Even running with sudo fails. I have tried running flyctl in the built-in Terminal.app but it gives the same error. I've given the .fly folder `chmod -R 777`, nada. It is creating the perms.* files with these permissions:

-rw-------   1 miika.henttonen  staff     0  9 Lok 11:27 perms.581431537

I can't think of anything else what I could do.

* Operating system: MacOS arm64 Sonoma 14.6.1 (23G93)
* Fly version: started with 0.3.14, tested now with 0.3.17, no change

`fly.toml`

```toml
app = "musa"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
```

** Command output: **

```text
Error: failed ensuring config directory perms: remove /Users/miika.henttonen/.fly/perms.3409036891: operation not permitted
```
