### ISSUE TITLE
fly launch with existing fly.toml replaces service port

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#401]
I have a config like this:

```toml
[metrics]
port = 9394
path = "/metrics"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    handlers = ["tls","http"]
    port = "443"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/status"
    protocol = "http"
    timeout = 2000
    headers = { Host = "health.check" }
```

When I run `fly launch` it offers to import it, so I do, but it replaces `internal_port = 3000` with `internal_port = 8080` so the deploy fails.
