### ISSUE TITLE
transformers.js not supported 

### ISSUE THREAD

**Issue by nilangablockstars** [superfly/flyctl#4101]
**Describe the bug**
When i try to deploy I get this below error

* Operating system
* `fly v0.3.45 darwin/amd64 Commit: d36714daf1a0bc2157649365827093e0948d9b1d BuildDate: 2024-12-02T15:41:58Z`

```toml
# fly.toml app configuration file generated for callx on 2024-09-12T10:56:42+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

kill_signal = "SIGINT"
kill_timeout = 10

app = 'callx'
primary_region = 'iad'

[build]

[env]
  PORT = 3000

[services]
  internal_port = 3000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [services.concurrency]
    type = "connections"
    hard_limit = 30
    soft_limit = 10

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = "15s"   # Check every 10 seconds
    timeout = "5s"     # Timeout after 2 seconds

[[vm]]
  memory = '1gb'
  cpu_kind = "shared"
  cpus = 1


```

** Command output: **

```text
Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/.pnpm/@xenova+transformers@2.17.2/node_modules/@xenova/transformers/src/transformers.js from /app/dist/index.js not supported.
```
