### ISSUE TITLE
`fly pg backup list` failed with deadline_exceeded sometimes

### ISSUE THREAD

**Issue by kubosuke** [superfly/flyctl#4194]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

when we execute `fly pg backup list`, it sometimes failed with deadline_exceeded

```
❯ f pg backup list -a prod-nexus-db-from-staging
Error: failed to exec on VM 2874262c353518: deadline_exceeded: Post "http://unix/v1/exec": net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Request ID: 01JJRPZ859TZM6BZ1A9RN4AZ5N-fra)
```

* Operating system

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```

* `fly version`

```
❯ f version
fly v0.3.70 darwin/arm64 Commit: 239bc529874fd0d24276eb3fdee0d79722ad0a34 BuildDate: 2025-01-28T18:39:08Z
```

** Paste your `fly.toml`

```toml
# fly.toml app configuration file generated for production-nexus on 2023-11-17T10:14:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "***"
primary_region = "fra"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"
  strategy = "bluegreen"

[env]
  DNS_CLUSTER_QUERY = "***"
  PHX_HOST = "***"
  PORT = "8080"
  PRIMARY_REGION = "fra"
  RELEASE_COOKIE = "***"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/_healthy"
    tls_skip_verify = false
```

** Command output: **

```text
❯ f pg backup list -a prod-nexus-db-from-staging
Error: failed to exec on VM 2874262c353518: deadline_exceeded: Post "http://unix/v1/exec": net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Request ID: 01JJRPZ859TZM6BZ1A9RN4AZ5N-fra)
```

fyi, Tigris and backup config

![Image](https://github.com/user-attachments/assets/615e4f05-e4fc-4ac7-9955-27f6bb36cd07)

```
❯ f pg backup config show -a ***
  ArchiveTimeout = 60s
  RecoveryWindow = 30d
  FullBackupFrequency = 1h
  MinimumRedundancy = 3
```
