### ISSUE TITLE
Not possible to validate configuration

### ISSUE THREAD

**Issue by skorotkiewicz** [superfly/flyctl#424]
When trying to deploy a simple test application to fly.io I keep getting an error that it cannot verify the configuration.
I also tried with [example node app](https://github.com/fly-apps/hellonode-builtin) from Fly.io, but it keeps showing the same error.

** `fly.toml` **

```toml
app = "myserver"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

```

** Command output: **

```text
$ flyctl deploy -v
Deploying myserver
==> Validating app configuration
Error not possible to validate configuration: server returned Could not resolve App
```
