### ISSUE TITLE
Neither fly launch and fly init --import copy fly.toml settings properly

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#426]
I have this `fly.toml` file:

```toml
app = "cockroachdb-example"

kill_signal = "SIGINT"
kill_timeout = 60

[metrics]
    port = 8080
    path = "/_status/vars"

[mount]
source="cdb_data"
destination="/cockroach/cockroach-data"

[experimental]
  cmd = ["shell", "start_fly.sh"]
```

When I run `fly launch` and elect to use the existing config, or `fly init --import fly.toml`, it doesn't actually keep these settings. Instead, it generates a new file like this:

```
# fly.toml file generated for wild-dew-3946 on 2021-06-07T21:06:49-05:00

app = "wild-dew-3946"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
```
