### ISSUE TITLE
`fly -c <config.toml> apps restart` doesn't pick up app name

### ISSUE THREAD

**Issue by benwaffle** [superfly/flyctl#4279]
**Describe the bug**
The only supported syntax is `fly apps restart <app-name>`. I would expect `fly -c <config.toml> apps restart` to also work.

* Operating system: macOS 15.3.1
* `fly version`: v0.3.94

** Paste your `fly.toml`

```toml
app = '...'
primary_region = 'iad'

[build]
  dockerfile = "apps/.../Dockerfile"

[deploy]
  release_command = 'sh -c "cd packages/db && pnpm run migrate"'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.http_options]
    h2_backend = true

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
```

** Command output: **

```text
Usage:
  fly apps restart <app name> [flags]
...
Error: unknown shorthand flag: 'c' in -c
```
