### ISSUE TITLE
flyctl launch creates unwanted .github/workflows/fly-deploy.yml

### ISSUE THREAD

**Issue by symkat** [superfly/flyctl#4386]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

When using `fly launch`, a file `.github/workflows/fly-deploy.yml` is automatically created (if .git/config contains "github" or a .github/ directory exists) and there is no way to prevent the file from being created.

Something like `fly launch --no-github-workflow` to prevent this was searched for, but not found.

* Operating system: MacOS
* `fly version`: fly v0.3.126 darwin/arm64 Commit: 4fc5b6ee88645cfd561e1f98c94376aa4a26b414 BuildDate: 2025-05-19T14:01:58

** Paste your `fly.toml`

(Used https://github.com/fly-apps/hello-fly)

```toml
# paste your config file here
# fly.toml app configuration file generated for hello-fly-sparkling-thunder-6097 on 2025-05-20T12:07:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-fly-sparkling-thunder-6097'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

```

** Command output: **

```text
$ git clone https://github.com/fly-apps/hello-fly.git
Cloning into 'hello-fly'...
...
$ cd hello-fly/
$ ls -la .github
ls: .github: No such file or directory
$ fly launch --yes
Scanning source code
Detected a Dockerfile app
...
Visit your newly deployed app at https://hello-fly-morning-sea-3904.fly.dev/
$ ls -la .github/
...
drwx------@  3 symkat  staff   96 May 20 13:12 workflows
$ ls -la .github/workflows/fly-deploy.yml
-rw-------@ 1 symkat  staff  495 May 20 13:12 .github/workflows/fly-deploy.yml
```

Thank you!
