### ISSUE TITLE
Fly launch does not work with Yarn package manager

### ISSUE THREAD

**Issue by spiralw** [superfly/flyctl#451]
Fly's docker build expects there to be a `package-lock.json`. Obviously, this doesn't exist when not using `npm` package manager.

## fly.toml:
``` toml
# fly.toml file generated for example on 2021-07-11T21:36:17-04:00

app = "example"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "node"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
```

## Command output:
```text
Step 4/10 : COPY package-lock.json .
Error error building: error rendering build status stream: COPY failed: file not found in build context or excluded by .dockerignore: stat package-lock.json: file does not exist
```
