### ISSUE TITLE
Files are being sent to docker build context that should be excluded via .dockerignore

### ISSUE THREAD

**Issue by loklaan** [superfly/flyctl#456]
While deploying an app I noticed that the size of the context being sent to the image builder (Docker) was much larger than expected. Gbs instead of Mbs.

I think this is because the patterns in my `.dockerignore` aren't being honoured? From what I've read around on the forums etc, this shouldn't be the case.

**Command Run:**

```
flyctl deploy
  --config support/flyio/focus-platform--opencourse-cms.fly.toml
  --dockerfile support/docker/Dockerfile.opencourse-backend.prod
```

**Directory Structure: _abridged_**

```
.
├── .dockerignore
├── app
│   └── opencourse-backend
├── support
│   ├── docker
│   │   └── Dockerfile.opencourse-backend.prod
│   └── flyio
│       └── focus-platform--opencourse-cms.fly.toml
└── yarn.lock
```

**`focus-platform--opencourse-cms.fly.toml`:**

```toml
app = "focus-platform--opencourse-cms"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]
  NODE_ENV = "production"

[experimental]
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

```

**`.dockerignore`:**

```ignore
# Yarn 2
.yarn/*
!.yarn/cache
!.yarn/releases
!.yarn/plugins
!.yarn/sdks
!.yarn/versions
.pnp.*

# Packages
node_modules
*/node_modules

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# IDEs and Editors
.idea
.project
.classpath
.c9
*.launch
.settings
*.sublime-workspace
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json

# OS
.DS_Store

# Git
.git

# Project Dist Files
app/opencourse-frontend/.next
app/opencourse-frontend/.fab
app/opencourse-frontend/out
app/opencourse-frontend/fab.zip
app/opencourse-backend/.keystone/admin/.next
```

**Command output:**

_Yup that's 10mins to archive and load just the context (ended up being +2gb)._

```text
Deploying focus-platform--opencourse-cms
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8080
==> Creating build context
--> Creating build context done
==> Building image with Docker
[+] Building 216.4s (0/1)
[+] Building 386.6s (23/23) FINISHED
 => [internal] load remote build context                                                                                                                                                                              0.0s
 => copy /context /                                                                                                                                                                                                  57.6s
```

---

Running `ncdu -X .dockerignore` lets me know I haven't made mistakes in the `.dockerignore`, and the size should be very small:
```
--- /...../focus-platform -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    3.6 MiB [###############################] /app
    1.1 MiB [#########                      ]  yarn.lock
  164.0 KiB [#                              ] /support
  132.0 KiB [#                              ] /package
   44.0 KiB [                               ] /.github
   20.0 KiB [                               ]  PROBLEMS.md
    4.0 KiB [                               ]  package.json
    4.0 KiB [                               ]  .eslintrc.js
    4.0 KiB [                               ]  .dockerignore
    4.0 KiB [                               ]  .prettierignore
    4.0 KiB [                               ]  .eslintignore
    4.0 KiB [                               ]  .gitignore
    4.0 KiB [                               ]  .yarnrc.yml
    4.0 KiB [                               ]  README.md
    4.0 KiB [                               ]  .editorconfig
    4.0 KiB [                               ]  .gitattributes
    4.0 KiB [                               ]  .prettierrc
    0.0   B [                               ] /.yarn
<   0.0   B [                               ]  node_modules
<   0.0   B [                               ]  .idea
<   0.0   B [                               ]  .git
<   0.0   B [                               ]  .DS_Store
```
