### ISSUE TITLE
`fly deploy` hangs after successful deployment and health checks

### ISSUE THREAD

**Issue by TimoFreiberg** [superfly/flyctl#460]
**Describe the bug**
Two runs in a row I had to cancel the github action manually ([first](https://github.com/TimoFreiberg/shopping-list/runs/3106238777?check_suite_focus=true), [second](https://github.com/TimoFreiberg/shopping-list/runs/3106486145?check_suite_focus=true)). The task idled for more than 10 minutes after the deployment was already successful
I don't want to use `--detach` because I want the job to fail if the deployment failed. 

** Add `fly.toml`

```toml
app = "shopping-list"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "shopping-list:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
```

** Command output: **

```text
/usr/bin/docker run --name a33c1eb21bc174b174910b0ef48c5f514cff7_d2e794 --label 8a33c1 --workdir /github/workspace --rm -e CARGO_TERM_COLOR -e FLY_API_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/shopping-list/shopping-list":"/github/workspace" 8a33c1:eb21bc174b174910b0ef48c5f514cff7 deploy
Deploying shopping-list
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8000
Searching for image 'shopping-list:latest' locally...
image found: sha256:b08d6cb6695b1f5a4fd0441894a873d0abb484d07b451bfe48528469e61ceff1
==> Pushing image to fly
The push refers to repository [registry.fly.io/shopping-list]
1b81273a5954: Preparing
9615736ad52e: Preparing
952ccb9947cb: Preparing
d0d3657cd9a1: Preparing
c84b90575ac7: Preparing
61b01195778f: Preparing
9371c13acb17: Preparing
764055ebc9a7: Preparing
61b01195778f: Waiting
9371c13acb17: Waiting
764055ebc9a7: Waiting
952ccb9947cb: Pushed
9615736ad52e: Pushed
d0d3657cd9a1: Pushed
1b81273a5954: Pushed
9371c13acb17: Pushed
61b01195778f: Pushed
c84b90575ac7: Pushed
764055ebc9a7: Pushed
deployment-1626715957: digest: sha256:989fe5f4c87a645e1cdbd4aca2b44db6229b012462e43ccd13c65526ad7f60b1 size: 1985
--> Pushing image done
Image: registry.fly.io/shopping-list:deployment-1626715957
Image size: 88 MB
==> Creating release
Release v17 created

You can detach the terminal anytime without stopping the deployment
Monitoring Deployment

v16 is being deployed
f99cc235: fra running healthy [health checks: 1 total, 1 passing]
f99cc235: fra complete healthy [health checks: 1 total, 1 passing]
Error: The operation was canceled.
```
