### ISSUE TITLE
Mount points should take owner/mode

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#632]
**Describe the bug**
Jupyter's base image does weird things to create the directory notebooks are stored in, so the base image doesn't work with Fly volumes.

** Add `fly.toml`

```toml
[[mounts]]
  destination = "/home/jovyan"
  source = "home_jovyan"
```

This wants also fields for owner = "jovyan" and mode = "0750".

Obvs, this implies backend changes too. Annoying! But it will make some out-of-the-box Dockerhub images work with volumes.
