### ISSUE TITLE
`flyio/flyctl:v0.0.270` yields warnings on `/.fly/config.yml` and `/.fly/state.yml`

### ISSUE THREAD

**Issue by DazWilkin** [superfly/flyctl#677]
**Describe the bug**

I prefer using the container image and it has been working well for me but, I noticed (after missing a few updates) that I now (any image tag including/after `v0.0.261`) receive warnings with e.g. `[flyctl] apps [create|list|destroy]` and `[flyctl] deploy --app=...`

Where `flyctl`:
```bash
VERS="v0.0.261"
podman run \
--interactive --tty --rm \
--volume=${PWD}/.fly:/.fly \
--volume=${PWD}/fly.toml:/fly.toml \
flyio/flyctl:${VERS}
```
And:
```console
drwxrw---- .fly

drwxrw-rw- .
drwxrwxr-x ..
drwx------ agent-logs
-rw-rw-r-- config.yml
srwxr-xr-x fly-agent.sock
-rw-rw-r-- state.yml
```
And:
```bash
more .fly/config.yml
access_token: [[REDACTED]]
update_check:
  latest_version: 0.0.210
  timestamp: "2021-04-14T20:38:03.621186489Z"
wire_guard_state: {}

more .fly/state.yml
channel: latest
last_checked_at: 2021-12-23T00:13:52.723618667Z
latest_release:
    version: v0.0.270
    prerelease: false
    download_url: https://github.com/superfly/flyctl/releases/download/v0.0.270/flyctl_0.0.270_Linux_x86_64.tar.gz
    timestamp: 2021-12-17T22:33:08Z
```
> **NOTE** `r/podman/docker` with the same outcome

```bash
WARN no config file found at /.fly/config.yml
...
WARN failed saving cache to /.fly/state.yml: open /tmp/flyctl.cache.lock: no such file or directory
```
I back-tracked and the warnings arose in `v0.0.261`:

** Add `fly.toml`

```toml
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "registry.fly.io/..."

[experimental]
  exec = [
    "/server",
    "--failure_rate=0.5",
    "--changes_rate=15s",
    "--endpoint=:50051"
  ]
  private_network = true

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["tls"]
    tls_options = {"alpn"=["h2"]}
    port = "10000"
```

** Command output: **

```text
VERS=v0.0.253
[flyctl] apps create freddie
Update available 0.0.253 -> v0.0.270.
Run "flyctl version update" to upgrade.
automatically selected personal organization: Daz Wilkin
New app created: freddie

[flyctl] apps list
Update available 0.0.253 -> v0.0.270.
Run "flyctl version update" to upgrade.
NAME        	OWNER   	STATUS 	LATEST DEPLOY 
freddie   	        personal	pending	             	

[flyctl] apps destroy freddie
Update available 0.0.253 -> v0.0.270.
Run "flyctl version update" to upgrade.
Destroying an app is not reversible.
? Destroy app freddie? Yes
Destroyed app freddie

VERS=v0.0.270
[flyctl] apps create freddie
WARN no config file found at /.fly/config.yml
Error OrganizationType isn't a defined input type (on $orgType)

VERS=v0.0.253
[flyctl] apps create freddie
Update available 0.0.253 -> v0.0.270.
Run "flyctl version update" to upgrade.
automatically selected personal organization: Daz Wilkin
New app created: freddie

VERS=v0.0.270
[flyctl] deploy --app=freddie
WARN no config file found at /.fly/config.yml
Deploying freddie
==> Validating app configuration
--> Validating app configuration done
Services
TCP 10000 ⇢ 50051
Searching for image 'registry.fly.io/...' remotely...
image found: img_3e1zd4m035yv02yw
Image: registry.fly.io/...
Image size: 7.3 MB
==> Creating release
WARN failed saving cache to /.fly/state.yml: open /tmp/flyctl.cache.lock: no such file or directory
```
