### ISSUE TITLE
Deploy with specified config file began failing in 0.272

### ISSUE THREAD

**Issue by zacwest** [superfly/flyctl#697]
**Describe the bug**
`fly deploy -c some.fly.toml` now fails with:

> Error failed to fetch an image or build from source: Rel: can't make Dockerfile relative to &lt;repo root>/Sources/PushServer

Note this is in a sub-directory in a repository.

Renaming to `fly.toml` does work, renaming it to `something-else.toml` does not work.

This began with 0.272 and worked with 0.271.

** Add `fly.toml` **

```toml
app = "haapns"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "info"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

** Command output: **

```
fly deploy -c app.fly.toml
==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-throbbing-fire-9599 ready
==> Creating build context
Error failed to fetch an image or build from source: Rel: can't make Dockerfile relative to /Users/zac/sources/hass-ios/Sources/PushServer
```
