### ISSUE TITLE
Action failing when deploy succeeds

### ISSUE THREAD

**Issue by matthewford** [superfly/flyctl#722]
The action logs show the deploy worked, but then errors:
```
--> v124 deployed successfully

--> Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

Github action
```
jobs:
  deploy:
    name: Deploy staging to fly
    runs-on: ubuntu-latest
    concurrency: staging_environment
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs `flyctl deploy`.
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy -c fly-ten-staging.toml -e APP_REVISION=${{ github.sha }}"
```
