### ISSUE TITLE
fly launch should create a volume when using an existing config with `[mounts]`

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#729]
When I run `fly launch` in a directory with this config:

```toml
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source="myapp_data"
  destination="/home/coder/project"
```

It should create the volume for me.  I believe all it needs to know is the size, at this stage we should already know the region. So if it prompts for size, then runs the equivalent of `fly volumes create myapp_data --size <size>` it'll be pretty magical.
