### ISSUE TITLE
Docs : flyctl.toml docs for experimental section do not match what is being generated client side

### ISSUE THREAD

**Issue by grempe** [superfly/flyctl#731]
**Describe the bug**

When you currently build a new app for deployment a default `fly.toml` file is created. It contains an `experimental` section that looks like:

```toml
[experimental]
  allowed_public_ports = []
  auto_rollback = true
```

However, the docs for this section:

https://fly.io/docs/reference/configuration/#the-experimental-section

do not mention or document either of those options and instead document two other options:

```toml
[experimental]
cmd = ["path/to/command", "arg1", "arg2"]
entrypoint = ["path/to/command", "arg1", "arg2"]
```

The documentation for the `experimental` section should reflect all experimental options.
