### ISSUE TITLE
Release task output in non-interactive deploys print some weird characters

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#795]
Example:

```
Running release task...⡿ WWWWWWWWWWWWWWWWWWWWWWWWWW

Running release task...⣟ WWWWWWWWWWWWWWWWWWWWWWWWWW

Running release task...⣯ WWWWWWWWWWWWWWWWWWWWWWWWWW

Running release task...⣷ WWWWWWWWWWWWWWWWWWWWWWWWWW
```

**Comment by jsierles** [comment]
Maybe related: the release task output in interactive mode now repeats output but never says 'Running release task'. Maybe interactive/non-interactive got reversed?

```
-> You can detach the terminal anytime without stopping the deployment
==> Release command detected: bundle exec rake db:migrate

--> This release will not be available until the release command succeeds.
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Preparing to run: `bundle exec rake db:migrate` as root
	 2022/02/02 16:31:16 listening on [fdaa:0:22b7:a7b:aa3:5b45:e620:2]:22 (DNS: [fdaa::3]:53)
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: 0c50bff)...
	 Preparing to run: `bundle exec rake db:migrate` as root
	 2022/02/02 16:31:16 listening on [fdaa:0:22b7:a7b:aa3:5b45:e620:2]:22 (DNS: [fdaa::3]:53)
	 Main child exited normally with code: 0
	 Starting clean up.
	 Main child exited normally with code: 0
	 Starting clean up.
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: 0c50bff)...
	 Preparing to run: `bundle exec rake db:migrate` as root
	 2022/02/02 16:31:16 listening on [fdaa:0:22b7:a7b:aa3:5b45:e620:2]:22 (DNS: [fdaa::3]:53)
	 Main child exited normally with code: 0
	 Starting clean up.
```

**Comment by astrophena** [comment]
Also encountered this problem when deploying with GitHub Actions. It hanged (I cancelled action manually) and printed nearly 40K lines of garbage: 

![image](https://user-images.githubusercontent.com/58525038/152391464-3f6acd73-5b03-4ddd-8f56-98eeca364373.png)

Here is the workflow file that I used:

```yaml
name: 'Deploy'
on:
  push:
    branches: ['master']
    paths-ignore:
      - 'vms/**' # I run 'nixos-rebuild switch' manually.
      - '*.md' # Don't redeploy when updating documentation.
jobs:
  services:
    name: 'Services'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        service:
          - 'go-import-redirector'
          - 'miniflux'
          - 'postgres'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v2.4.0'
        with:
          fetch-depth: 0
      - name: 'Check if deployment is needed'
        id: 'changed-files'
        uses: 'tj-actions/changed-files@v14.3'
        with:
          files: services/${{ matrix.service }}
      - name: 'Deploy'
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: 'superfly/flyctl-actions@master'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_PROJECT_PATH: services/${{ matrix.service }}
        with:
          args: 'deploy'
```
