### ISSUE TITLE
fly launch fails from lack of volumes even when declining postgres database

### ISSUE THREAD

**Issue by manigandham** [superfly/flyctl#857]
`fly launch` fails to deploy when declining postgres database (due to lack of volumes in region), but volume isn't needed when there's no database to launch.

* windows 11
* `fly.exe v0.0.303 windows/amd64 Commit: d09e39d BuildDate: 2022-03-08T00:22:46Z`

```toml
# fly.toml file generated for throbbing-breeze-3543 on 2022-03-07T23:22:43-08:00

app = "throbbing-breeze-3543"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

```text
PS C:\dev\nproxy> fly launch
Creating app in C:\dev\nproxy
Scanning source code
Detected a Dockerfile app
? App Name (leave blank to use an auto-generated name):
Automatically selected personal organization: MG
? Select region: lax (Los Angeles, California (US))
Created app throbbing-breeze-3543 in organization personal
Wrote config file fly.toml
? Would you like to setup a Postgresql database now? No
? Would you like to deploy now? Yes
Deploying throbbing-breeze-3543
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8080
Error error connecting to docker: Couldn't allocate volume, no disks available (region: lax, size_gb: 50)
```
