### ISSUE TITLE
Creating Volume for App in one particular region(SIN) automatically shifts App to another region 

### ISSUE THREAD

**Issue by KosmonautX** [superfly/flyctl#902]
**Describe the bug**
Is this behavior because its not possible to create a volume in Singapore? If so why does the volume still label itself as being situated in Singapore

* Operating system
`5.16.16-arch1-1`

* fly version
`flyctl v0.0.308 linux/amd64`

```toml
app = "$APP"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "$APP.fly.dev"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```
```
fly volumes create archive --region sin
        ID: vol_w1q85vgjdk8vzdxe
      Name: archive
       App: $APP
    Region: sin
      Zone: 0417
   Size GB: 10
 Encrypted: true
Created at: 03 Apr 22 15:38 UTC
```
THough the volume states the region as sin, the app automatically undergoes a release shifting region to GRU and MAD 

Attempting to revert back to sin prompts me to delete the volume instead
fly regions add sin
Error App '$APP' uses volumes to control regions. Add or remove volumes to change region placement.

**Comment by mrkurt** [comment]
Volumes are unattached when you create them. You need to add a section to your config to make your app use a volume:

```toml
[mounts]
  source = "archive"
  destination = "/data"
```

The error you're hitting is a validation on our end that doesn't really make sense when the volume is unmounted. We should still let you control regions when volumes aren't actually being used.
