### ISSUE TITLE
Naming services

### ISSUE THREAD

**Issue by jeromegn** [superfly/flyctl#95]
Service names would be more friendly and identifiable in future features (such as metrics).

Example configuration:

```toml
[services.web]
  internal_port = 8080
  protocol = "tcp"

  [services.web.concurrency]
    hard_limit = 80
    soft_limit = 20

  [[services.web.http_checks]]
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 1000
    tls_skip_verify = false

  [[services.web.ports]]
    handlers = ["http"]
    port = "80"

  [[services.web.ports]]
    handlers = ["tls", "http"]
    port = "443"
```

This would probably look better with hcl ;)
