### ISSUE TITLE
failed building options: failed probing "personal": context deadline exceeded

### ISSUE THREAD

**Issue by skorotkiewicz** [superfly/flyctl#950]
```sh
LOG_LEVEL=debug flyctl deploy --remote-only
```

```log
DEBUG <-- 200 https://api.fly.io/graphql (294.14ms) {"data":{"validateWireGuardPeers":{"invalidPeerIps":[]}}}
DEBUG result image:<nil> error:error connecting to docker: failed building options: failed probing "personal": context deadline exceeded
```

* macOS Big Sur
* `flyctl v0.0.324 darwin/amd64 Commit: dcb5132 BuildDate: 2022-04-26T13:51:01Z`

```toml
app = "appname"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```
