### ISSUE TITLE
Error We need your payment information to continue! Add a credit card or buy credit. But I have credits

### ISSUE THREAD

**Issue by runar-rkmedia** [superfly/flyctl#981]
This was also posted in: https://community.fly.io/t/error-we-need-you-payment-information-to-continue-even-though-i-have-added-my-card-and-have-credits-lets/5299/2

*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

I deployed my application multiple times yesterday. Today I cannot update the image with `fly deploy`, which results in the error:

> Error We need your payment information to continue! Add a credit card or buy credit: https://fly.io/organizations/personal

I have deposited $25 a few months ago, and haven't spent any of it yes. I tried adding another $25 to maybe reset the billing-state, but that did not help.

* Operating system
macOs Monteray version 12.3.1
Darwin x.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

* `fly version`
* fly v0.0.328 darwin/amd64 Commit: be3bfa2 BuildDate: 2022-05-18T15:02:10Z

** Paste your `fly.toml`
```toml
# https://fly.io/docs/reference/configuration/

app = "skiver"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[build]
  image = "runardocker/skiver-api:latest"

[deploy]
  strategy = "rolling"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
port = 9091 # default for most prometheus clients
path = "/metrics" # default for most prometheus clients
[[mounts]]
source="skiver_data"
destination="/storage"
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    # Until postgres is available, we don't really support concurrency
    hard_limit = 999999
    soft_limit = 999999
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

```toml
# paste your config file here
```

** Command output: **

```text
 fly deploy
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'runardocker/skiver-api:latest' locally...
image found: sha256:a3a1e5f91472be0ce9b1382d014e6465d387db851a2dc752b9bab692236b9a64
==> Pushing image to fly
The push refers to repository [registry.fly.io/skiver]
818813db1e4d: Layer already exists
e946a62a8fc6: Layer already exists
6778876886ff: Layer already exists
deployment-1653330040: digest: sha256:c0dee9a9e16771945d579b7bd3ba94cfd8ab58a79cf2bb23eb1db7c6c864f139 size: 945
--> Pushing image done
==> Creating release
Error We need your payment information to continue! Add a credit card or buy credit: https://fly.io/organizations/personal

```
